// Code generated by scripts/generate-address-policy.mjs; DO NOT EDIT.

package policy

const AddressPolicyID = "zeroproxy-address-policy-v1"

var blockedAddressSuffixes = [...]string{
	"alt",
	"arpa",
	"corp",
	"example",
	"example.com",
	"example.net",
	"example.org",
	"home",
	"home.arpa",
	"internal",
	"invalid",
	"lan",
	"local",
	"localdomain",
	"localhost",
	"metadata.aws.internal",
	"metadata.azure.internal",
	"metadata.google.internal",
	"onion",
	"test",
}
