// Code generated by scripts/generate-errors.mjs. DO NOT EDIT.
package errorauthority

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
)

const (
	SchemaVersion = 1
	ErrorVersion  = 2
)

type ErrorStage string
type ErrorCode string

const (
	StageBootstrap            ErrorStage = "BOOTSTRAP"
	StageCoordinator          ErrorStage = "COORDINATOR"
	StageRoute                ErrorStage = "ROUTE"
	StagePolicy               ErrorStage = "POLICY"
	StageRewriteHtml          ErrorStage = "REWRITE_HTML"
	StageRewriteJs            ErrorStage = "REWRITE_JS"
	StageRewriteCss           ErrorStage = "REWRITE_CSS"
	StageImportMap            ErrorStage = "IMPORT_MAP"
	StageRuntimeInstall       ErrorStage = "RUNTIME_INSTALL"
	StageRelay                ErrorStage = "RELAY"
	StageSmux                 ErrorStage = "SMUX"
	StageSocks                ErrorStage = "SOCKS"
	StageTls                  ErrorStage = "TLS"
	StageHttp                 ErrorStage = "HTTP"
	StageCors                 ErrorStage = "CORS"
	StageBody                 ErrorStage = "BODY"
	StageWebsocket            ErrorStage = "WEBSOCKET"
	StageCookie               ErrorStage = "COOKIE"
	StageStorage              ErrorStage = "STORAGE"
	StageVirtualServiceWorker ErrorStage = "VIRTUAL_SERVICE_WORKER"
	StageInternal             ErrorStage = "INTERNAL"
)

const (
	CodeAbiIdentifierCollision         ErrorCode = "ABI_IDENTIFIER_COLLISION"
	CodeAbiVersionMismatch             ErrorCode = "ABI_VERSION_MISMATCH"
	CodeBodyChunkEmpty                 ErrorCode = "BODY_CHUNK_EMPTY"
	CodeBodyChunkInvalid               ErrorCode = "BODY_CHUNK_INVALID"
	CodeBodyChunkLimit                 ErrorCode = "BODY_CHUNK_LIMIT"
	CodeBodySequence                   ErrorCode = "BODY_SEQUENCE"
	CodeBootstrapFailed                ErrorCode = "BOOTSTRAP_FAILED"
	CodeBootstrapStateViolation        ErrorCode = "BOOTSTRAP_STATE_VIOLATION"
	CodeBrowserUnsupported             ErrorCode = "BROWSER_UNSUPPORTED"
	CodeCanceled                       ErrorCode = "CANCELED"
	CodeCancelCode                     ErrorCode = "CANCEL_CODE"
	CodeCancelSequence                 ErrorCode = "CANCEL_SEQUENCE"
	CodeCapabilityRejected             ErrorCode = "CAPABILITY_REJECTED"
	CodeClientAbort                    ErrorCode = "CLIENT_ABORT"
	CodeCodegenFailed                  ErrorCode = "CODEGEN_FAILED"
	CodeConnectTimeout                 ErrorCode = "CONNECT_TIMEOUT"
	CodeControlOriginRejected          ErrorCode = "CONTROL_ORIGIN_REJECTED"
	CodeControlOriginUnavailable       ErrorCode = "CONTROL_ORIGIN_UNAVAILABLE"
	CodeCookieContextInvalid           ErrorCode = "COOKIE_CONTEXT_INVALID"
	CodeCookieCoreRejected             ErrorCode = "COOKIE_CORE_REJECTED"
	CodeCookieCoreUnavailable          ErrorCode = "COOKIE_CORE_UNAVAILABLE"
	CodeCookieSequenceStale            ErrorCode = "COOKIE_SEQUENCE_STALE"
	CodeCookieStateCorrupt             ErrorCode = "COOKIE_STATE_CORRUPT"
	CodeCookieStateUnavailable         ErrorCode = "COOKIE_STATE_UNAVAILABLE"
	CodeCoordinatorFailed              ErrorCode = "COORDINATOR_FAILED"
	CodeCoordinatorRevisionCorrupt     ErrorCode = "COORDINATOR_REVISION_CORRUPT"
	CodeCoordinatorUnavailable         ErrorCode = "COORDINATOR_UNAVAILABLE"
	CodeCorsFailed                     ErrorCode = "CORS_FAILED"
	CodeCredentialsModeInvalid         ErrorCode = "CREDENTIALS_MODE_INVALID"
	CodeCssRewriteFailed               ErrorCode = "CSS_REWRITE_FAILED"
	CodeDnsResolution                  ErrorCode = "DNS_RESOLUTION"
	CodeDocumentCspInvalid             ErrorCode = "DOCUMENT_CSP_INVALID"
	CodeDocumentEncodingUnsupported    ErrorCode = "DOCUMENT_ENCODING_UNSUPPORTED"
	CodeDocumentRouteRejected          ErrorCode = "DOCUMENT_ROUTE_REJECTED"
	CodeDownloadBackpressure           ErrorCode = "DOWNLOAD_BACKPRESSURE"
	CodeDownloadChunkLimit             ErrorCode = "DOWNLOAD_CHUNK_LIMIT"
	CodeDownloadSequence               ErrorCode = "DOWNLOAD_SEQUENCE"
	CodeDuplicateOperation             ErrorCode = "DUPLICATE_OPERATION"
	CodeErrorCode                      ErrorCode = "ERROR_CODE"
	CodeErrorSequence                  ErrorCode = "ERROR_SEQUENCE"
	CodeEventDelivery                  ErrorCode = "EVENT_DELIVERY"
	CodeFailurePageAssetMissing        ErrorCode = "FAILURE_PAGE_ASSET_MISSING"
	CodeForbiddenHeader                ErrorCode = "FORBIDDEN_HEADER"
	CodeFrameType                      ErrorCode = "FRAME_TYPE"
	CodeHandoffRejected                ErrorCode = "HANDOFF_REJECTED"
	CodeHeaderInvalid                  ErrorCode = "HEADER_INVALID"
	CodeHeaderLimit                    ErrorCode = "HEADER_LIMIT"
	CodeHistoryRouteFailed             ErrorCode = "HISTORY_ROUTE_FAILED"
	CodeHostBindingRejected            ErrorCode = "HOST_BINDING_REJECTED"
	CodeHostConfigurationRejected      ErrorCode = "HOST_CONFIGURATION_REJECTED"
	CodeHostConfigurationTimeout       ErrorCode = "HOST_CONFIGURATION_TIMEOUT"
	CodeHostContextRejected            ErrorCode = "HOST_CONTEXT_REJECTED"
	CodeHtmlRewriteFailed              ErrorCode = "HTML_REWRITE_FAILED"
	CodeHttpParse                      ErrorCode = "HTTP_PARSE"
	CodeHttpTimeout                    ErrorCode = "HTTP_TIMEOUT"
	CodeImportMapInvalid               ErrorCode = "IMPORT_MAP_INVALID"
	CodeInternalFailed                 ErrorCode = "INTERNAL_FAILED"
	CodeInvalidAddress                 ErrorCode = "INVALID_ADDRESS"
	CodeInvalidMessage                 ErrorCode = "INVALID_MESSAGE"
	CodeInvalidScope                   ErrorCode = "INVALID_SCOPE"
	CodeInvalidSourceKind              ErrorCode = "INVALID_SOURCE_KIND"
	CodeInvalidSpecifierKey            ErrorCode = "INVALID_SPECIFIER_KEY"
	CodeKernelId                       ErrorCode = "KERNEL_ID"
	CodeMessageSchema                  ErrorCode = "MESSAGE_SCHEMA"
	CodeMessageVersion                 ErrorCode = "MESSAGE_VERSION"
	CodeOriginInvalid                  ErrorCode = "ORIGIN_INVALID"
	CodeParseFailed                    ErrorCode = "PARSE_FAILED"
	CodePersonaBinding                 ErrorCode = "PERSONA_BINDING"
	CodePlanContextInvalid             ErrorCode = "PLAN_CONTEXT_INVALID"
	CodePlanIdInvalid                  ErrorCode = "PLAN_ID_INVALID"
	CodePlanReplay                     ErrorCode = "PLAN_REPLAY"
	CodePolicyBlocked                  ErrorCode = "POLICY_BLOCKED"
	CodePolicyDenied                   ErrorCode = "POLICY_DENIED"
	CodePortRequestLimit               ErrorCode = "PORT_REQUEST_LIMIT"
	CodePullLimit                      ErrorCode = "PULL_LIMIT"
	CodePullOutstanding                ErrorCode = "PULL_OUTSTANDING"
	CodeRelayCapabilityProfileMismatch ErrorCode = "RELAY_CAPABILITY_PROFILE_MISMATCH"
	CodeRelayLost                      ErrorCode = "RELAY_LOST"
	CodeRelayLostUnsafe                ErrorCode = "RELAY_LOST_UNSAFE"
	CodeRelayProfileConfigUnavailable  ErrorCode = "RELAY_PROFILE_CONFIG_UNAVAILABLE"
	CodeRelayProfileNotInstalled       ErrorCode = "RELAY_PROFILE_NOT_INSTALLED"
	CodeRelayProfileSetMismatch        ErrorCode = "RELAY_PROFILE_SET_MISMATCH"
	CodeRelayUnavailable               ErrorCode = "RELAY_UNAVAILABLE"
	CodeReleaseGateFailed              ErrorCode = "RELEASE_GATE_FAILED"
	CodeReplayDetected                 ErrorCode = "REPLAY_DETECTED"
	CodeRequestBinding                 ErrorCode = "REQUEST_BINDING"
	CodeRequestContextInvalid          ErrorCode = "REQUEST_CONTEXT_INVALID"
	CodeRequestFailed                  ErrorCode = "REQUEST_FAILED"
	CodeRequestIdInvalid               ErrorCode = "REQUEST_ID_INVALID"
	CodeRequestIdReplay                ErrorCode = "REQUEST_ID_REPLAY"
	CodeRequestNotActive               ErrorCode = "REQUEST_NOT_ACTIVE"
	CodeRequestTerminal                ErrorCode = "REQUEST_TERMINAL"
	CodeResolutionFailed               ErrorCode = "RESOLUTION_FAILED"
	CodeResourceTooLarge               ErrorCode = "RESOURCE_TOO_LARGE"
	CodeResponseBody                   ErrorCode = "RESPONSE_BODY"
	CodeRewriteFailed                  ErrorCode = "REWRITE_FAILED"
	CodeRouteClassMismatch             ErrorCode = "ROUTE_CLASS_MISMATCH"
	CodeRouteExpired                   ErrorCode = "ROUTE_EXPIRED"
	CodeRouteInvalid                   ErrorCode = "ROUTE_INVALID"
	CodeRouteNotFound                  ErrorCode = "ROUTE_NOT_FOUND"
	CodeRouteUnavailable               ErrorCode = "ROUTE_UNAVAILABLE"
	CodeRuntimeAssetMissing            ErrorCode = "RUNTIME_ASSET_MISSING"
	CodeRuntimeInstallFailed           ErrorCode = "RUNTIME_INSTALL_FAILED"
	CodeScriptKindInvalid              ErrorCode = "SCRIPT_KIND_INVALID"
	CodeSealedRoutePolicyDenied        ErrorCode = "SEALED_ROUTE_POLICY_DENIED"
	CodeSealedRouteTargetFailed        ErrorCode = "SEALED_ROUTE_TARGET_FAILED"
	CodeServerCloseFailed              ErrorCode = "SERVER_CLOSE_FAILED"
	CodeServerFailed                   ErrorCode = "SERVER_FAILED"
	CodeServerHttpError                ErrorCode = "SERVER_HTTP_ERROR"
	CodeServiceWorkerRejected          ErrorCode = "SERVICE_WORKER_REJECTED"
	CodeServiceWorkerScopeRejected     ErrorCode = "SERVICE_WORKER_SCOPE_REJECTED"
	CodeServiceWorkerTimeout           ErrorCode = "SERVICE_WORKER_TIMEOUT"
	CodeServiceWorkerUnavailable       ErrorCode = "SERVICE_WORKER_UNAVAILABLE"
	CodeSmuxProtocol                   ErrorCode = "SMUX_PROTOCOL"
	CodeSmuxStreamLimit                ErrorCode = "SMUX_STREAM_LIMIT"
	CodeSocksPolicy                    ErrorCode = "SOCKS_POLICY"
	CodeSocksProtocol                  ErrorCode = "SOCKS_PROTOCOL"
	CodeSocksReply                     ErrorCode = "SOCKS_REPLY"
	CodeStaleOperation                 ErrorCode = "STALE_OPERATION"
	CodeStorageFailed                  ErrorCode = "STORAGE_FAILED"
	CodeStreamIdleTimeout              ErrorCode = "STREAM_IDLE_TIMEOUT"
	CodeStreamLimit                    ErrorCode = "STREAM_LIMIT"
	CodeStreamTotalTimeout             ErrorCode = "STREAM_TOTAL_TIMEOUT"
	CodeTargetAddressPolicy            ErrorCode = "TARGET_ADDRESS_POLICY"
	CodeTargetCertificate              ErrorCode = "TARGET_CERTIFICATE"
	CodeTargetCoepBlocked              ErrorCode = "TARGET_COEP_BLOCKED"
	CodeTargetCspBlocked               ErrorCode = "TARGET_CSP_BLOCKED"
	CodeTargetCspInvalid               ErrorCode = "TARGET_CSP_INVALID"
	CodeTargetDocumentPolicyInvalid    ErrorCode = "TARGET_DOCUMENT_POLICY_INVALID"
	CodeTargetFetchFailed              ErrorCode = "TARGET_FETCH_FAILED"
	CodeTargetFramePolicyBlocked       ErrorCode = "TARGET_FRAME_POLICY_BLOCKED"
	CodeTargetPortBlocked              ErrorCode = "TARGET_PORT_BLOCKED"
	CodeTargetUrl                      ErrorCode = "TARGET_URL"
	CodeTargetUrlInvalid               ErrorCode = "TARGET_URL_INVALID"
	CodeTargetWorkerFetchFailed        ErrorCode = "TARGET_WORKER_FETCH_FAILED"
	CodeTargetWorkerHostRejected       ErrorCode = "TARGET_WORKER_HOST_REJECTED"
	CodeTargetWorkerHostUnavailable    ErrorCode = "TARGET_WORKER_HOST_UNAVAILABLE"
	CodeTargetWorkerJournalCorrupt     ErrorCode = "TARGET_WORKER_JOURNAL_CORRUPT"
	CodeTargetWorkerStateUnavailable   ErrorCode = "TARGET_WORKER_STATE_UNAVAILABLE"
	CodeTcpConnect                     ErrorCode = "TCP_CONNECT"
	CodeTlsAlpn                        ErrorCode = "TLS_ALPN"
	CodeTlsConnect                     ErrorCode = "TLS_CONNECT"
	CodeTlsProtocol                    ErrorCode = "TLS_PROTOCOL"
	CodeTlsTimeout                     ErrorCode = "TLS_TIMEOUT"
	CodeTransformFailed                ErrorCode = "TRANSFORM_FAILED"
	CodeUnknownOperation               ErrorCode = "UNKNOWN_OPERATION"
	CodeUnknownRequest                 ErrorCode = "UNKNOWN_REQUEST"
	CodeUnsupportedBrowserSyntax       ErrorCode = "UNSUPPORTED_BROWSER_SYNTAX"
	CodeUnsupportedDirectEvalBinding   ErrorCode = "UNSUPPORTED_DIRECT_EVAL_BINDING"
	CodeUnsupportedDirectEvalShape     ErrorCode = "UNSUPPORTED_DIRECT_EVAL_SHAPE"
	CodeUnsupportedDynamicScope        ErrorCode = "UNSUPPORTED_DYNAMIC_SCOPE"
	CodeUnsupportedImportScriptsShape  ErrorCode = "UNSUPPORTED_IMPORT_SCRIPTS_SHAPE"
	CodeUploadQueueFull                ErrorCode = "UPLOAD_QUEUE_FULL"
	CodeUploadReadError                ErrorCode = "UPLOAD_READ_ERROR"
	CodeVirtualServiceWorkerFailed     ErrorCode = "VIRTUAL_SERVICE_WORKER_FAILED"
	CodeWebsocketCloseInvalid          ErrorCode = "WEBSOCKET_CLOSE_INVALID"
	CodeWebsocketMessageInvalid        ErrorCode = "WEBSOCKET_MESSAGE_INVALID"
	CodeWebsocketProtocolInvalid       ErrorCode = "WEBSOCKET_PROTOCOL_INVALID"
	CodeWebsocketSendQueueFull         ErrorCode = "WEBSOCKET_SEND_QUEUE_FULL"
	CodeWebsocketSequence              ErrorCode = "WEBSOCKET_SEQUENCE"
	CodeWebsocketState                 ErrorCode = "WEBSOCKET_STATE"
	CodeWebsocketTerminal              ErrorCode = "WEBSOCKET_TERMINAL"
)

type errorSpecification struct {
	stages     []ErrorStage
	retryable  bool
	messageKey string
}

func specification(code ErrorCode) (errorSpecification, bool) {
	switch code {
	case CodeAbiIdentifierCollision:
		return errorSpecification{stages: []ErrorStage{StageRewriteJs}, retryable: false, messageKey: "rewrite_js_blocked"}, true
	case CodeAbiVersionMismatch:
		return errorSpecification{stages: []ErrorStage{StageRewriteJs}, retryable: false, messageKey: "rewrite_js_version_mismatch"}, true
	case CodeBodyChunkEmpty:
		return errorSpecification{stages: []ErrorStage{StageBody}, retryable: false, messageKey: "body_invalid"}, true
	case CodeBodyChunkInvalid:
		return errorSpecification{stages: []ErrorStage{StageBody}, retryable: false, messageKey: "body_invalid"}, true
	case CodeBodyChunkLimit:
		return errorSpecification{stages: []ErrorStage{StageBody}, retryable: false, messageKey: "body_limit"}, true
	case CodeBodySequence:
		return errorSpecification{stages: []ErrorStage{StageBody}, retryable: false, messageKey: "body_sequence_invalid"}, true
	case CodeBootstrapFailed:
		return errorSpecification{stages: []ErrorStage{StageBootstrap}, retryable: false, messageKey: "bootstrap_failed"}, true
	case CodeBootstrapStateViolation:
		return errorSpecification{stages: []ErrorStage{StageBootstrap}, retryable: false, messageKey: "bootstrap_failed"}, true
	case CodeBrowserUnsupported:
		return errorSpecification{stages: []ErrorStage{StageBootstrap}, retryable: false, messageKey: "browser_unsupported"}, true
	case CodeCanceled:
		return errorSpecification{stages: []ErrorStage{StageBody}, retryable: false, messageKey: "request_canceled"}, true
	case CodeCancelCode:
		return errorSpecification{stages: []ErrorStage{StageBody}, retryable: false, messageKey: "body_cancel_invalid"}, true
	case CodeCancelSequence:
		return errorSpecification{stages: []ErrorStage{StageBody}, retryable: false, messageKey: "body_sequence_invalid"}, true
	case CodeCapabilityRejected:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "capability_rejected"}, true
	case CodeClientAbort:
		return errorSpecification{stages: []ErrorStage{StageSocks, StageTls, StageHttp}, retryable: false, messageKey: "request_canceled"}, true
	case CodeCodegenFailed:
		return errorSpecification{stages: []ErrorStage{StageRewriteJs}, retryable: false, messageKey: "rewrite_js_failed"}, true
	case CodeConnectTimeout:
		return errorSpecification{stages: []ErrorStage{StageSocks}, retryable: true, messageKey: "target_connect_timeout"}, true
	case CodeControlOriginRejected:
		return errorSpecification{stages: []ErrorStage{StageBootstrap}, retryable: false, messageKey: "control_origin_rejected"}, true
	case CodeControlOriginUnavailable:
		return errorSpecification{stages: []ErrorStage{StageBootstrap}, retryable: true, messageKey: "control_origin_unavailable"}, true
	case CodeCookieContextInvalid:
		return errorSpecification{stages: []ErrorStage{StagePolicy, StageCookie}, retryable: false, messageKey: "cookie_context_invalid"}, true
	case CodeCookieCoreRejected:
		return errorSpecification{stages: []ErrorStage{StageCookie}, retryable: false, messageKey: "cookie_update_rejected"}, true
	case CodeCookieCoreUnavailable:
		return errorSpecification{stages: []ErrorStage{StageCookie}, retryable: false, messageKey: "cookie_service_unavailable"}, true
	case CodeCookieSequenceStale:
		return errorSpecification{stages: []ErrorStage{StagePolicy, StageCookie}, retryable: false, messageKey: "cookie_sequence_stale"}, true
	case CodeCookieStateCorrupt:
		return errorSpecification{stages: []ErrorStage{StageCookie}, retryable: false, messageKey: "cookie_state_invalid"}, true
	case CodeCookieStateUnavailable:
		return errorSpecification{stages: []ErrorStage{StageCookie}, retryable: true, messageKey: "cookie_service_unavailable"}, true
	case CodeCoordinatorFailed:
		return errorSpecification{stages: []ErrorStage{StageCoordinator}, retryable: false, messageKey: "coordinator_failed"}, true
	case CodeCoordinatorRevisionCorrupt:
		return errorSpecification{stages: []ErrorStage{StageCoordinator}, retryable: false, messageKey: "coordinator_state_invalid"}, true
	case CodeCoordinatorUnavailable:
		return errorSpecification{stages: []ErrorStage{StageCoordinator}, retryable: true, messageKey: "coordinator_unavailable"}, true
	case CodeCorsFailed:
		return errorSpecification{stages: []ErrorStage{StageCors}, retryable: false, messageKey: "network_request_failed"}, true
	case CodeCredentialsModeInvalid:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "request_policy_blocked"}, true
	case CodeCssRewriteFailed:
		return errorSpecification{stages: []ErrorStage{StageRewriteCss}, retryable: false, messageKey: "rewrite_css_failed"}, true
	case CodeDnsResolution:
		return errorSpecification{stages: []ErrorStage{StageSocks}, retryable: true, messageKey: "target_dns_failed"}, true
	case CodeDocumentCspInvalid:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "target_policy_blocked"}, true
	case CodeDocumentEncodingUnsupported:
		return errorSpecification{stages: []ErrorStage{StageRewriteHtml}, retryable: false, messageKey: "rewrite_html_failed"}, true
	case CodeDocumentRouteRejected:
		return errorSpecification{stages: []ErrorStage{StageRoute}, retryable: false, messageKey: "route_invalid"}, true
	case CodeDownloadBackpressure:
		return errorSpecification{stages: []ErrorStage{StageBody}, retryable: false, messageKey: "body_backpressure"}, true
	case CodeDownloadChunkLimit:
		return errorSpecification{stages: []ErrorStage{StageBody}, retryable: false, messageKey: "body_limit"}, true
	case CodeDownloadSequence:
		return errorSpecification{stages: []ErrorStage{StageBody}, retryable: false, messageKey: "body_sequence_invalid"}, true
	case CodeDuplicateOperation:
		return errorSpecification{stages: []ErrorStage{StageCoordinator}, retryable: false, messageKey: "duplicate_operation"}, true
	case CodeErrorCode:
		return errorSpecification{stages: []ErrorStage{StageBody}, retryable: false, messageKey: "body_error_invalid"}, true
	case CodeErrorSequence:
		return errorSpecification{stages: []ErrorStage{StageBody}, retryable: false, messageKey: "body_sequence_invalid"}, true
	case CodeEventDelivery:
		return errorSpecification{stages: []ErrorStage{StageBody}, retryable: false, messageKey: "body_delivery_failed"}, true
	case CodeFailurePageAssetMissing:
		return errorSpecification{stages: []ErrorStage{StageRuntimeInstall}, retryable: false, messageKey: "runtime_install_failed"}, true
	case CodeForbiddenHeader:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "request_policy_blocked"}, true
	case CodeFrameType:
		return errorSpecification{stages: []ErrorStage{StageBody}, retryable: false, messageKey: "body_frame_invalid"}, true
	case CodeHandoffRejected:
		return errorSpecification{stages: []ErrorStage{StageBootstrap}, retryable: false, messageKey: "handoff_rejected"}, true
	case CodeHeaderInvalid:
		return errorSpecification{stages: []ErrorStage{StageHttp}, retryable: false, messageKey: "http_header_invalid"}, true
	case CodeHeaderLimit:
		return errorSpecification{stages: []ErrorStage{StageHttp}, retryable: false, messageKey: "http_header_limit"}, true
	case CodeHistoryRouteFailed:
		return errorSpecification{stages: []ErrorStage{StageRoute}, retryable: true, messageKey: "route_expired"}, true
	case CodeHostBindingRejected:
		return errorSpecification{stages: []ErrorStage{StageBootstrap}, retryable: false, messageKey: "host_binding_rejected"}, true
	case CodeHostConfigurationRejected:
		return errorSpecification{stages: []ErrorStage{StageBootstrap}, retryable: false, messageKey: "host_configuration_rejected"}, true
	case CodeHostConfigurationTimeout:
		return errorSpecification{stages: []ErrorStage{StageBootstrap}, retryable: true, messageKey: "host_configuration_timeout"}, true
	case CodeHostContextRejected:
		return errorSpecification{stages: []ErrorStage{StageBootstrap}, retryable: false, messageKey: "host_context_rejected"}, true
	case CodeHtmlRewriteFailed:
		return errorSpecification{stages: []ErrorStage{StageRewriteHtml}, retryable: false, messageKey: "rewrite_html_failed"}, true
	case CodeHttpParse:
		return errorSpecification{stages: []ErrorStage{StageHttp}, retryable: false, messageKey: "http_response_invalid"}, true
	case CodeHttpTimeout:
		return errorSpecification{stages: []ErrorStage{StageHttp}, retryable: true, messageKey: "http_timeout"}, true
	case CodeImportMapInvalid:
		return errorSpecification{stages: []ErrorStage{StageImportMap}, retryable: false, messageKey: "import_map_invalid"}, true
	case CodeInternalFailed:
		return errorSpecification{stages: []ErrorStage{StageInternal}, retryable: false, messageKey: "internal_failed"}, true
	case CodeInvalidAddress:
		return errorSpecification{stages: []ErrorStage{StageImportMap}, retryable: false, messageKey: "import_map_invalid"}, true
	case CodeInvalidMessage:
		return errorSpecification{stages: []ErrorStage{StageCoordinator}, retryable: false, messageKey: "invalid_message"}, true
	case CodeInvalidScope:
		return errorSpecification{stages: []ErrorStage{StageImportMap}, retryable: false, messageKey: "import_map_invalid"}, true
	case CodeInvalidSourceKind:
		return errorSpecification{stages: []ErrorStage{StageRewriteJs}, retryable: false, messageKey: "rewrite_js_source_invalid"}, true
	case CodeInvalidSpecifierKey:
		return errorSpecification{stages: []ErrorStage{StageImportMap}, retryable: false, messageKey: "import_map_invalid"}, true
	case CodeKernelId:
		return errorSpecification{stages: []ErrorStage{StageInternal}, retryable: false, messageKey: "internal_protocol_invalid"}, true
	case CodeMessageSchema:
		return errorSpecification{stages: []ErrorStage{StageInternal}, retryable: false, messageKey: "internal_protocol_invalid"}, true
	case CodeMessageVersion:
		return errorSpecification{stages: []ErrorStage{StageInternal}, retryable: false, messageKey: "internal_version_mismatch"}, true
	case CodeOriginInvalid:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "request_policy_blocked"}, true
	case CodeParseFailed:
		return errorSpecification{stages: []ErrorStage{StageRewriteJs}, retryable: false, messageKey: "rewrite_js_syntax_invalid"}, true
	case CodePersonaBinding:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "request_policy_blocked"}, true
	case CodePlanContextInvalid:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "request_policy_blocked"}, true
	case CodePlanIdInvalid:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "request_policy_blocked"}, true
	case CodePlanReplay:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "request_replay_blocked"}, true
	case CodePolicyBlocked:
		return errorSpecification{stages: []ErrorStage{StagePolicy, StageRewriteJs}, retryable: false, messageKey: "request_policy_blocked"}, true
	case CodePolicyDenied:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "request_policy_blocked"}, true
	case CodePortRequestLimit:
		return errorSpecification{stages: []ErrorStage{StageCoordinator}, retryable: false, messageKey: "coordinator_request_limit"}, true
	case CodePullLimit:
		return errorSpecification{stages: []ErrorStage{StageBody}, retryable: false, messageKey: "body_limit"}, true
	case CodePullOutstanding:
		return errorSpecification{stages: []ErrorStage{StageBody}, retryable: false, messageKey: "body_sequence_invalid"}, true
	case CodeRelayCapabilityProfileMismatch:
		return errorSpecification{stages: []ErrorStage{StageRelay}, retryable: false, messageKey: "relay_profile_invalid"}, true
	case CodeRelayLost:
		return errorSpecification{stages: []ErrorStage{StageRelay}, retryable: true, messageKey: "relay_connection_lost"}, true
	case CodeRelayLostUnsafe:
		return errorSpecification{stages: []ErrorStage{StageRelay}, retryable: false, messageKey: "relay_connection_lost"}, true
	case CodeRelayProfileConfigUnavailable:
		return errorSpecification{stages: []ErrorStage{StageRelay}, retryable: false, messageKey: "relay_profile_unavailable"}, true
	case CodeRelayProfileNotInstalled:
		return errorSpecification{stages: []ErrorStage{StageRelay}, retryable: false, messageKey: "relay_profile_unavailable"}, true
	case CodeRelayProfileSetMismatch:
		return errorSpecification{stages: []ErrorStage{StageRelay}, retryable: false, messageKey: "relay_profile_invalid"}, true
	case CodeRelayUnavailable:
		return errorSpecification{stages: []ErrorStage{StageRelay}, retryable: true, messageKey: "relay_unavailable"}, true
	case CodeReleaseGateFailed:
		return errorSpecification{stages: []ErrorStage{StageInternal}, retryable: false, messageKey: "release_gate_failed"}, true
	case CodeReplayDetected:
		return errorSpecification{stages: []ErrorStage{StageCoordinator}, retryable: false, messageKey: "replay_detected"}, true
	case CodeRequestBinding:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "request_policy_blocked"}, true
	case CodeRequestContextInvalid:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "request_policy_blocked"}, true
	case CodeRequestFailed:
		return errorSpecification{stages: []ErrorStage{StageInternal}, retryable: false, messageKey: "internal_failed"}, true
	case CodeRequestIdInvalid:
		return errorSpecification{stages: []ErrorStage{StageInternal}, retryable: false, messageKey: "internal_protocol_invalid"}, true
	case CodeRequestIdReplay:
		return errorSpecification{stages: []ErrorStage{StageInternal}, retryable: false, messageKey: "internal_replay_detected"}, true
	case CodeRequestNotActive:
		return errorSpecification{stages: []ErrorStage{StageInternal}, retryable: false, messageKey: "internal_request_inactive"}, true
	case CodeRequestTerminal:
		return errorSpecification{stages: []ErrorStage{StageHttp, StageBody}, retryable: false, messageKey: "request_already_finished"}, true
	case CodeResolutionFailed:
		return errorSpecification{stages: []ErrorStage{StageRewriteJs}, retryable: false, messageKey: "rewrite_js_failed"}, true
	case CodeResourceTooLarge:
		return errorSpecification{stages: []ErrorStage{StageRewriteHtml, StageRewriteJs, StageRewriteCss, StageImportMap, StageBody}, retryable: false, messageKey: "resource_too_large"}, true
	case CodeResponseBody:
		return errorSpecification{stages: []ErrorStage{StageBody}, retryable: true, messageKey: "response_body_failed"}, true
	case CodeRewriteFailed:
		return errorSpecification{stages: []ErrorStage{StageRewriteHtml}, retryable: false, messageKey: "rewrite_html_failed"}, true
	case CodeRouteClassMismatch:
		return errorSpecification{stages: []ErrorStage{StageRoute}, retryable: false, messageKey: "route_invalid"}, true
	case CodeRouteExpired:
		return errorSpecification{stages: []ErrorStage{StageRoute}, retryable: true, messageKey: "route_expired"}, true
	case CodeRouteInvalid:
		return errorSpecification{stages: []ErrorStage{StageRoute}, retryable: false, messageKey: "route_invalid"}, true
	case CodeRouteNotFound:
		return errorSpecification{stages: []ErrorStage{StageRoute}, retryable: false, messageKey: "route_not_found"}, true
	case CodeRouteUnavailable:
		return errorSpecification{stages: []ErrorStage{StageRoute}, retryable: true, messageKey: "route_expired"}, true
	case CodeRuntimeAssetMissing:
		return errorSpecification{stages: []ErrorStage{StageRuntimeInstall}, retryable: false, messageKey: "runtime_install_failed"}, true
	case CodeRuntimeInstallFailed:
		return errorSpecification{stages: []ErrorStage{StageRuntimeInstall}, retryable: false, messageKey: "runtime_install_failed"}, true
	case CodeScriptKindInvalid:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "script_policy_blocked"}, true
	case CodeSealedRoutePolicyDenied:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "request_policy_blocked"}, true
	case CodeSealedRouteTargetFailed:
		return errorSpecification{stages: []ErrorStage{StageHttp}, retryable: true, messageKey: "network_request_failed"}, true
	case CodeServerCloseFailed:
		return errorSpecification{stages: []ErrorStage{StageSmux, StageSocks, StageWebsocket}, retryable: false, messageKey: "internal_failed"}, true
	case CodeServerFailed:
		return errorSpecification{stages: []ErrorStage{StageBootstrap}, retryable: false, messageKey: "internal_failed"}, true
	case CodeServerHttpError:
		return errorSpecification{stages: []ErrorStage{StageInternal}, retryable: false, messageKey: "internal_failed"}, true
	case CodeServiceWorkerRejected:
		return errorSpecification{stages: []ErrorStage{StageBootstrap}, retryable: false, messageKey: "service_worker_rejected"}, true
	case CodeServiceWorkerScopeRejected:
		return errorSpecification{stages: []ErrorStage{StageBootstrap}, retryable: false, messageKey: "service_worker_rejected"}, true
	case CodeServiceWorkerTimeout:
		return errorSpecification{stages: []ErrorStage{StageBootstrap}, retryable: true, messageKey: "service_worker_unavailable"}, true
	case CodeServiceWorkerUnavailable:
		return errorSpecification{stages: []ErrorStage{StageBootstrap}, retryable: true, messageKey: "service_worker_unavailable"}, true
	case CodeSmuxProtocol:
		return errorSpecification{stages: []ErrorStage{StageSmux}, retryable: false, messageKey: "relay_protocol_failed"}, true
	case CodeSmuxStreamLimit:
		return errorSpecification{stages: []ErrorStage{StageSmux}, retryable: true, messageKey: "relay_stream_limit"}, true
	case CodeSocksPolicy:
		return errorSpecification{stages: []ErrorStage{StageSocks}, retryable: false, messageKey: "target_policy_blocked"}, true
	case CodeSocksProtocol:
		return errorSpecification{stages: []ErrorStage{StageSocks}, retryable: false, messageKey: "target_connect_failed"}, true
	case CodeSocksReply:
		return errorSpecification{stages: []ErrorStage{StageSocks}, retryable: true, messageKey: "target_connect_failed"}, true
	case CodeStaleOperation:
		return errorSpecification{stages: []ErrorStage{StageCoordinator}, retryable: true, messageKey: "stale_operation"}, true
	case CodeStorageFailed:
		return errorSpecification{stages: []ErrorStage{StageStorage}, retryable: false, messageKey: "storage_failed"}, true
	case CodeStreamIdleTimeout:
		return errorSpecification{stages: []ErrorStage{StageBody}, retryable: true, messageKey: "body_timeout"}, true
	case CodeStreamLimit:
		return errorSpecification{stages: []ErrorStage{StageRelay}, retryable: true, messageKey: "relay_stream_limit"}, true
	case CodeStreamTotalTimeout:
		return errorSpecification{stages: []ErrorStage{StageBody}, retryable: true, messageKey: "body_timeout"}, true
	case CodeTargetAddressPolicy:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "target_policy_blocked"}, true
	case CodeTargetCertificate:
		return errorSpecification{stages: []ErrorStage{StageTls}, retryable: false, messageKey: "target_certificate_failed"}, true
	case CodeTargetCoepBlocked:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "target_policy_blocked"}, true
	case CodeTargetCspBlocked:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "target_policy_blocked"}, true
	case CodeTargetCspInvalid:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "target_policy_blocked"}, true
	case CodeTargetDocumentPolicyInvalid:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "target_policy_blocked"}, true
	case CodeTargetFetchFailed:
		return errorSpecification{stages: []ErrorStage{StageHttp}, retryable: true, messageKey: "network_request_failed"}, true
	case CodeTargetFramePolicyBlocked:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "target_policy_blocked"}, true
	case CodeTargetPortBlocked:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "target_port_blocked"}, true
	case CodeTargetUrl:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "target_url_invalid"}, true
	case CodeTargetUrlInvalid:
		return errorSpecification{stages: []ErrorStage{StagePolicy}, retryable: false, messageKey: "target_url_invalid"}, true
	case CodeTargetWorkerFetchFailed:
		return errorSpecification{stages: []ErrorStage{StageVirtualServiceWorker}, retryable: true, messageKey: "virtual_service_worker_unavailable"}, true
	case CodeTargetWorkerHostRejected:
		return errorSpecification{stages: []ErrorStage{StageVirtualServiceWorker}, retryable: false, messageKey: "virtual_service_worker_failed"}, true
	case CodeTargetWorkerHostUnavailable:
		return errorSpecification{stages: []ErrorStage{StageVirtualServiceWorker}, retryable: true, messageKey: "virtual_service_worker_unavailable"}, true
	case CodeTargetWorkerJournalCorrupt:
		return errorSpecification{stages: []ErrorStage{StageVirtualServiceWorker}, retryable: false, messageKey: "virtual_service_worker_state_invalid"}, true
	case CodeTargetWorkerStateUnavailable:
		return errorSpecification{stages: []ErrorStage{StageVirtualServiceWorker}, retryable: true, messageKey: "virtual_service_worker_unavailable"}, true
	case CodeTcpConnect:
		return errorSpecification{stages: []ErrorStage{StageSocks}, retryable: true, messageKey: "target_connect_failed"}, true
	case CodeTlsAlpn:
		return errorSpecification{stages: []ErrorStage{StageTls}, retryable: false, messageKey: "target_tls_failed"}, true
	case CodeTlsConnect:
		return errorSpecification{stages: []ErrorStage{StageTls}, retryable: false, messageKey: "target_tls_failed"}, true
	case CodeTlsProtocol:
		return errorSpecification{stages: []ErrorStage{StageTls}, retryable: false, messageKey: "target_tls_failed"}, true
	case CodeTlsTimeout:
		return errorSpecification{stages: []ErrorStage{StageTls}, retryable: true, messageKey: "target_tls_timeout"}, true
	case CodeTransformFailed:
		return errorSpecification{stages: []ErrorStage{StageRewriteJs}, retryable: false, messageKey: "rewrite_js_failed"}, true
	case CodeUnknownOperation:
		return errorSpecification{stages: []ErrorStage{StageCoordinator}, retryable: false, messageKey: "unknown_operation"}, true
	case CodeUnknownRequest:
		return errorSpecification{stages: []ErrorStage{StageRoute}, retryable: false, messageKey: "route_invalid"}, true
	case CodeUnsupportedBrowserSyntax:
		return errorSpecification{stages: []ErrorStage{StageRewriteJs}, retryable: false, messageKey: "rewrite_js_syntax_unsupported"}, true
	case CodeUnsupportedDirectEvalBinding:
		return errorSpecification{stages: []ErrorStage{StageRewriteJs}, retryable: false, messageKey: "rewrite_js_policy_blocked"}, true
	case CodeUnsupportedDirectEvalShape:
		return errorSpecification{stages: []ErrorStage{StageRewriteJs}, retryable: false, messageKey: "rewrite_js_policy_blocked"}, true
	case CodeUnsupportedDynamicScope:
		return errorSpecification{stages: []ErrorStage{StageRewriteJs}, retryable: false, messageKey: "rewrite_js_policy_blocked"}, true
	case CodeUnsupportedImportScriptsShape:
		return errorSpecification{stages: []ErrorStage{StageRewriteJs}, retryable: false, messageKey: "rewrite_js_policy_blocked"}, true
	case CodeUploadQueueFull:
		return errorSpecification{stages: []ErrorStage{StageBody}, retryable: true, messageKey: "body_backpressure"}, true
	case CodeUploadReadError:
		return errorSpecification{stages: []ErrorStage{StageBody}, retryable: false, messageKey: "body_upload_failed"}, true
	case CodeVirtualServiceWorkerFailed:
		return errorSpecification{stages: []ErrorStage{StageVirtualServiceWorker}, retryable: false, messageKey: "virtual_service_worker_failed"}, true
	case CodeWebsocketCloseInvalid:
		return errorSpecification{stages: []ErrorStage{StageWebsocket}, retryable: false, messageKey: "websocket_protocol_invalid"}, true
	case CodeWebsocketMessageInvalid:
		return errorSpecification{stages: []ErrorStage{StageWebsocket}, retryable: false, messageKey: "websocket_protocol_invalid"}, true
	case CodeWebsocketProtocolInvalid:
		return errorSpecification{stages: []ErrorStage{StageWebsocket}, retryable: false, messageKey: "websocket_protocol_invalid"}, true
	case CodeWebsocketSendQueueFull:
		return errorSpecification{stages: []ErrorStage{StageWebsocket}, retryable: true, messageKey: "websocket_backpressure"}, true
	case CodeWebsocketSequence:
		return errorSpecification{stages: []ErrorStage{StageWebsocket}, retryable: false, messageKey: "websocket_protocol_invalid"}, true
	case CodeWebsocketState:
		return errorSpecification{stages: []ErrorStage{StageWebsocket}, retryable: false, messageKey: "websocket_failed"}, true
	case CodeWebsocketTerminal:
		return errorSpecification{stages: []ErrorStage{StageWebsocket}, retryable: false, messageKey: "websocket_failed"}, true
	default:
		return errorSpecification{}, false
	}
}

type InternalError struct {
	Code          ErrorCode  `json:"code"`
	Stage         ErrorStage `json:"stage"`
	Retryable     bool       `json:"retryable"`
	RequestID     string     `json:"request_id"`
	InternalCause any        `json:"internal_cause"`
}

type PublicError struct {
	Code       ErrorCode  `json:"code"`
	Stage      ErrorStage `json:"stage"`
	Retryable  bool       `json:"retryable"`
	RequestID  string     `json:"request_id"`
	MessageKey string     `json:"message_key"`
}

func validRequestID(value string) bool {
	if len(value) < 16 || len(value) > 64 {
		return false
	}
	for _, character := range value {
		if !((character >= 'a' && character <= 'z') || (character >= 'A' && character <= 'Z') || (character >= '0' && character <= '9') || character == '_' || character == '-') {
			return false
		}
	}
	return true
}

func validateVersion(errorVersion int) error {
	if errorVersion != ErrorVersion {
		return fmt.Errorf("unknown error version %d", errorVersion)
	}
	return nil
}

func validateCommon(code ErrorCode, stage ErrorStage, retryable bool, requestID string) (errorSpecification, error) {
	specificationValue, known := specification(code)
	if !known {
		return errorSpecification{}, fmt.Errorf("unknown error code %q", code)
	}
	stageAllowed := false
	for _, allowed := range specificationValue.stages {
		stageAllowed = stageAllowed || allowed == stage
	}
	if !stageAllowed {
		return errorSpecification{}, fmt.Errorf("invalid stage %q for error code %q", stage, code)
	}
	if retryable != specificationValue.retryable {
		return errorSpecification{}, fmt.Errorf("invalid retryable value for error code %q", code)
	}
	if !validRequestID(requestID) {
		return errorSpecification{}, fmt.Errorf("invalid request ID")
	}
	return specificationValue, nil
}

func NewInternal(errorVersion int, code ErrorCode, stage ErrorStage, requestID string, internalCause any) (InternalError, error) {
	if err := validateVersion(errorVersion); err != nil {
		return InternalError{}, err
	}
	specificationValue, err := validateCommon(code, stage, specificationRetryable(code), requestID)
	if err != nil {
		return InternalError{}, err
	}
	if _, err := json.Marshal(internalCause); err != nil {
		return InternalError{}, fmt.Errorf("invalid internal cause: %w", err)
	}
	return InternalError{Code: code, Stage: stage, Retryable: specificationValue.retryable, RequestID: requestID, InternalCause: internalCause}, nil
}

func specificationRetryable(code ErrorCode) bool {
	specificationValue, known := specification(code)
	return known && specificationValue.retryable
}

func (value InternalError) Validate(errorVersion int) error {
	if err := validateVersion(errorVersion); err != nil {
		return err
	}
	if _, err := validateCommon(value.Code, value.Stage, value.Retryable, value.RequestID); err != nil {
		return err
	}
	if _, err := json.Marshal(value.InternalCause); err != nil {
		return fmt.Errorf("invalid internal cause: %w", err)
	}
	return nil
}

func (value InternalError) Public(errorVersion int) (PublicError, error) {
	if err := value.Validate(errorVersion); err != nil {
		return PublicError{}, err
	}
	specificationValue, _ := specification(value.Code)
	return PublicError{Code: value.Code, Stage: value.Stage, Retryable: value.Retryable, RequestID: value.RequestID, MessageKey: specificationValue.messageKey}, nil
}

func (value PublicError) Validate(errorVersion int) error {
	if err := validateVersion(errorVersion); err != nil {
		return err
	}
	specificationValue, err := validateCommon(value.Code, value.Stage, value.Retryable, value.RequestID)
	if err != nil {
		return err
	}
	if value.MessageKey != specificationValue.messageKey {
		return fmt.Errorf("invalid message key for error code %q", value.Code)
	}
	return nil
}

func decodeExact(data []byte, destination any) error {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(destination); err != nil {
		return err
	}
	if err := decoder.Decode(&struct{}{}); err != io.EOF {
		return fmt.Errorf("trailing error envelope data")
	}
	return nil
}

func DecodeInternal(errorVersion int, data []byte) (InternalError, error) {
	var value InternalError
	if err := decodeExact(data, &value); err != nil {
		return InternalError{}, err
	}
	return value, value.Validate(errorVersion)
}

func DecodePublic(errorVersion int, data []byte) (PublicError, error) {
	var value PublicError
	if err := decodeExact(data, &value); err != nil {
		return PublicError{}, err
	}
	return value, value.Validate(errorVersion)
}
