// Generated by scripts/generate-errors.mjs. DO NOT EDIT.
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::fmt;

pub const ERROR_SCHEMA_VERSION: u16 = 1;
pub const ERROR_VERSION: u16 = 2;

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum ErrorStage {
    #[serde(rename = "BOOTSTRAP")]
    Bootstrap,
    #[serde(rename = "COORDINATOR")]
    Coordinator,
    #[serde(rename = "ROUTE")]
    Route,
    #[serde(rename = "POLICY")]
    Policy,
    #[serde(rename = "REWRITE_HTML")]
    RewriteHtml,
    #[serde(rename = "REWRITE_JS")]
    RewriteJs,
    #[serde(rename = "REWRITE_CSS")]
    RewriteCss,
    #[serde(rename = "IMPORT_MAP")]
    ImportMap,
    #[serde(rename = "RUNTIME_INSTALL")]
    RuntimeInstall,
    #[serde(rename = "RELAY")]
    Relay,
    #[serde(rename = "SMUX")]
    Smux,
    #[serde(rename = "SOCKS")]
    Socks,
    #[serde(rename = "TLS")]
    Tls,
    #[serde(rename = "HTTP")]
    Http,
    #[serde(rename = "CORS")]
    Cors,
    #[serde(rename = "BODY")]
    Body,
    #[serde(rename = "WEBSOCKET")]
    Websocket,
    #[serde(rename = "COOKIE")]
    Cookie,
    #[serde(rename = "STORAGE")]
    Storage,
    #[serde(rename = "VIRTUAL_SERVICE_WORKER")]
    VirtualServiceWorker,
    #[serde(rename = "INTERNAL")]
    Internal,
}

#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub enum ErrorCode {
    #[serde(rename = "ABI_IDENTIFIER_COLLISION")]
    AbiIdentifierCollision,
    #[serde(rename = "ABI_VERSION_MISMATCH")]
    AbiVersionMismatch,
    #[serde(rename = "BODY_CHUNK_EMPTY")]
    BodyChunkEmpty,
    #[serde(rename = "BODY_CHUNK_INVALID")]
    BodyChunkInvalid,
    #[serde(rename = "BODY_CHUNK_LIMIT")]
    BodyChunkLimit,
    #[serde(rename = "BODY_SEQUENCE")]
    BodySequence,
    #[serde(rename = "BOOTSTRAP_FAILED")]
    BootstrapFailed,
    #[serde(rename = "BOOTSTRAP_STATE_VIOLATION")]
    BootstrapStateViolation,
    #[serde(rename = "BROWSER_UNSUPPORTED")]
    BrowserUnsupported,
    #[serde(rename = "CANCELED")]
    Canceled,
    #[serde(rename = "CANCEL_CODE")]
    CancelCode,
    #[serde(rename = "CANCEL_SEQUENCE")]
    CancelSequence,
    #[serde(rename = "CAPABILITY_REJECTED")]
    CapabilityRejected,
    #[serde(rename = "CLIENT_ABORT")]
    ClientAbort,
    #[serde(rename = "CODEGEN_FAILED")]
    CodegenFailed,
    #[serde(rename = "CONNECT_TIMEOUT")]
    ConnectTimeout,
    #[serde(rename = "CONTROL_ORIGIN_REJECTED")]
    ControlOriginRejected,
    #[serde(rename = "CONTROL_ORIGIN_UNAVAILABLE")]
    ControlOriginUnavailable,
    #[serde(rename = "COOKIE_CONTEXT_INVALID")]
    CookieContextInvalid,
    #[serde(rename = "COOKIE_CORE_REJECTED")]
    CookieCoreRejected,
    #[serde(rename = "COOKIE_CORE_UNAVAILABLE")]
    CookieCoreUnavailable,
    #[serde(rename = "COOKIE_SEQUENCE_STALE")]
    CookieSequenceStale,
    #[serde(rename = "COOKIE_STATE_CORRUPT")]
    CookieStateCorrupt,
    #[serde(rename = "COOKIE_STATE_UNAVAILABLE")]
    CookieStateUnavailable,
    #[serde(rename = "COORDINATOR_FAILED")]
    CoordinatorFailed,
    #[serde(rename = "COORDINATOR_REVISION_CORRUPT")]
    CoordinatorRevisionCorrupt,
    #[serde(rename = "COORDINATOR_UNAVAILABLE")]
    CoordinatorUnavailable,
    #[serde(rename = "CORS_FAILED")]
    CorsFailed,
    #[serde(rename = "CREDENTIALS_MODE_INVALID")]
    CredentialsModeInvalid,
    #[serde(rename = "CSS_REWRITE_FAILED")]
    CssRewriteFailed,
    #[serde(rename = "DNS_RESOLUTION")]
    DnsResolution,
    #[serde(rename = "DOCUMENT_CSP_INVALID")]
    DocumentCspInvalid,
    #[serde(rename = "DOCUMENT_ENCODING_UNSUPPORTED")]
    DocumentEncodingUnsupported,
    #[serde(rename = "DOCUMENT_ROUTE_REJECTED")]
    DocumentRouteRejected,
    #[serde(rename = "DOWNLOAD_BACKPRESSURE")]
    DownloadBackpressure,
    #[serde(rename = "DOWNLOAD_CHUNK_LIMIT")]
    DownloadChunkLimit,
    #[serde(rename = "DOWNLOAD_SEQUENCE")]
    DownloadSequence,
    #[serde(rename = "DUPLICATE_OPERATION")]
    DuplicateOperation,
    #[serde(rename = "ERROR_CODE")]
    ErrorCode,
    #[serde(rename = "ERROR_SEQUENCE")]
    ErrorSequence,
    #[serde(rename = "EVENT_DELIVERY")]
    EventDelivery,
    #[serde(rename = "FAILURE_PAGE_ASSET_MISSING")]
    FailurePageAssetMissing,
    #[serde(rename = "FORBIDDEN_HEADER")]
    ForbiddenHeader,
    #[serde(rename = "FRAME_TYPE")]
    FrameType,
    #[serde(rename = "HANDOFF_REJECTED")]
    HandoffRejected,
    #[serde(rename = "HEADER_INVALID")]
    HeaderInvalid,
    #[serde(rename = "HEADER_LIMIT")]
    HeaderLimit,
    #[serde(rename = "HISTORY_ROUTE_FAILED")]
    HistoryRouteFailed,
    #[serde(rename = "HOST_BINDING_REJECTED")]
    HostBindingRejected,
    #[serde(rename = "HOST_CONFIGURATION_REJECTED")]
    HostConfigurationRejected,
    #[serde(rename = "HOST_CONFIGURATION_TIMEOUT")]
    HostConfigurationTimeout,
    #[serde(rename = "HOST_CONTEXT_REJECTED")]
    HostContextRejected,
    #[serde(rename = "HTML_REWRITE_FAILED")]
    HtmlRewriteFailed,
    #[serde(rename = "HTTP_PARSE")]
    HttpParse,
    #[serde(rename = "HTTP_TIMEOUT")]
    HttpTimeout,
    #[serde(rename = "IMPORT_MAP_INVALID")]
    ImportMapInvalid,
    #[serde(rename = "INTERNAL_FAILED")]
    InternalFailed,
    #[serde(rename = "INVALID_ADDRESS")]
    InvalidAddress,
    #[serde(rename = "INVALID_MESSAGE")]
    InvalidMessage,
    #[serde(rename = "INVALID_SCOPE")]
    InvalidScope,
    #[serde(rename = "INVALID_SOURCE_KIND")]
    InvalidSourceKind,
    #[serde(rename = "INVALID_SPECIFIER_KEY")]
    InvalidSpecifierKey,
    #[serde(rename = "KERNEL_ID")]
    KernelId,
    #[serde(rename = "MESSAGE_SCHEMA")]
    MessageSchema,
    #[serde(rename = "MESSAGE_VERSION")]
    MessageVersion,
    #[serde(rename = "ORIGIN_INVALID")]
    OriginInvalid,
    #[serde(rename = "PARSE_FAILED")]
    ParseFailed,
    #[serde(rename = "PERSONA_BINDING")]
    PersonaBinding,
    #[serde(rename = "PLAN_CONTEXT_INVALID")]
    PlanContextInvalid,
    #[serde(rename = "PLAN_ID_INVALID")]
    PlanIdInvalid,
    #[serde(rename = "PLAN_REPLAY")]
    PlanReplay,
    #[serde(rename = "POLICY_BLOCKED")]
    PolicyBlocked,
    #[serde(rename = "POLICY_DENIED")]
    PolicyDenied,
    #[serde(rename = "PORT_REQUEST_LIMIT")]
    PortRequestLimit,
    #[serde(rename = "PULL_LIMIT")]
    PullLimit,
    #[serde(rename = "PULL_OUTSTANDING")]
    PullOutstanding,
    #[serde(rename = "RELAY_CAPABILITY_PROFILE_MISMATCH")]
    RelayCapabilityProfileMismatch,
    #[serde(rename = "RELAY_LOST")]
    RelayLost,
    #[serde(rename = "RELAY_LOST_UNSAFE")]
    RelayLostUnsafe,
    #[serde(rename = "RELAY_PROFILE_CONFIG_UNAVAILABLE")]
    RelayProfileConfigUnavailable,
    #[serde(rename = "RELAY_PROFILE_NOT_INSTALLED")]
    RelayProfileNotInstalled,
    #[serde(rename = "RELAY_PROFILE_SET_MISMATCH")]
    RelayProfileSetMismatch,
    #[serde(rename = "RELAY_UNAVAILABLE")]
    RelayUnavailable,
    #[serde(rename = "RELEASE_GATE_FAILED")]
    ReleaseGateFailed,
    #[serde(rename = "REPLAY_DETECTED")]
    ReplayDetected,
    #[serde(rename = "REQUEST_BINDING")]
    RequestBinding,
    #[serde(rename = "REQUEST_CONTEXT_INVALID")]
    RequestContextInvalid,
    #[serde(rename = "REQUEST_FAILED")]
    RequestFailed,
    #[serde(rename = "REQUEST_ID_INVALID")]
    RequestIdInvalid,
    #[serde(rename = "REQUEST_ID_REPLAY")]
    RequestIdReplay,
    #[serde(rename = "REQUEST_NOT_ACTIVE")]
    RequestNotActive,
    #[serde(rename = "REQUEST_TERMINAL")]
    RequestTerminal,
    #[serde(rename = "RESOLUTION_FAILED")]
    ResolutionFailed,
    #[serde(rename = "RESOURCE_TOO_LARGE")]
    ResourceTooLarge,
    #[serde(rename = "RESPONSE_BODY")]
    ResponseBody,
    #[serde(rename = "REWRITE_FAILED")]
    RewriteFailed,
    #[serde(rename = "ROUTE_CLASS_MISMATCH")]
    RouteClassMismatch,
    #[serde(rename = "ROUTE_EXPIRED")]
    RouteExpired,
    #[serde(rename = "ROUTE_INVALID")]
    RouteInvalid,
    #[serde(rename = "ROUTE_NOT_FOUND")]
    RouteNotFound,
    #[serde(rename = "ROUTE_UNAVAILABLE")]
    RouteUnavailable,
    #[serde(rename = "RUNTIME_ASSET_MISSING")]
    RuntimeAssetMissing,
    #[serde(rename = "RUNTIME_INSTALL_FAILED")]
    RuntimeInstallFailed,
    #[serde(rename = "SCRIPT_KIND_INVALID")]
    ScriptKindInvalid,
    #[serde(rename = "SEALED_ROUTE_POLICY_DENIED")]
    SealedRoutePolicyDenied,
    #[serde(rename = "SEALED_ROUTE_TARGET_FAILED")]
    SealedRouteTargetFailed,
    #[serde(rename = "SERVER_CLOSE_FAILED")]
    ServerCloseFailed,
    #[serde(rename = "SERVER_FAILED")]
    ServerFailed,
    #[serde(rename = "SERVER_HTTP_ERROR")]
    ServerHttpError,
    #[serde(rename = "SERVICE_WORKER_REJECTED")]
    ServiceWorkerRejected,
    #[serde(rename = "SERVICE_WORKER_SCOPE_REJECTED")]
    ServiceWorkerScopeRejected,
    #[serde(rename = "SERVICE_WORKER_TIMEOUT")]
    ServiceWorkerTimeout,
    #[serde(rename = "SERVICE_WORKER_UNAVAILABLE")]
    ServiceWorkerUnavailable,
    #[serde(rename = "SMUX_PROTOCOL")]
    SmuxProtocol,
    #[serde(rename = "SMUX_STREAM_LIMIT")]
    SmuxStreamLimit,
    #[serde(rename = "SOCKS_POLICY")]
    SocksPolicy,
    #[serde(rename = "SOCKS_PROTOCOL")]
    SocksProtocol,
    #[serde(rename = "SOCKS_REPLY")]
    SocksReply,
    #[serde(rename = "STALE_OPERATION")]
    StaleOperation,
    #[serde(rename = "STORAGE_FAILED")]
    StorageFailed,
    #[serde(rename = "STREAM_IDLE_TIMEOUT")]
    StreamIdleTimeout,
    #[serde(rename = "STREAM_LIMIT")]
    StreamLimit,
    #[serde(rename = "STREAM_TOTAL_TIMEOUT")]
    StreamTotalTimeout,
    #[serde(rename = "TARGET_ADDRESS_POLICY")]
    TargetAddressPolicy,
    #[serde(rename = "TARGET_CERTIFICATE")]
    TargetCertificate,
    #[serde(rename = "TARGET_COEP_BLOCKED")]
    TargetCoepBlocked,
    #[serde(rename = "TARGET_CSP_BLOCKED")]
    TargetCspBlocked,
    #[serde(rename = "TARGET_CSP_INVALID")]
    TargetCspInvalid,
    #[serde(rename = "TARGET_DOCUMENT_POLICY_INVALID")]
    TargetDocumentPolicyInvalid,
    #[serde(rename = "TARGET_FETCH_FAILED")]
    TargetFetchFailed,
    #[serde(rename = "TARGET_FRAME_POLICY_BLOCKED")]
    TargetFramePolicyBlocked,
    #[serde(rename = "TARGET_PORT_BLOCKED")]
    TargetPortBlocked,
    #[serde(rename = "TARGET_URL")]
    TargetUrl,
    #[serde(rename = "TARGET_URL_INVALID")]
    TargetUrlInvalid,
    #[serde(rename = "TARGET_WORKER_FETCH_FAILED")]
    TargetWorkerFetchFailed,
    #[serde(rename = "TARGET_WORKER_HOST_REJECTED")]
    TargetWorkerHostRejected,
    #[serde(rename = "TARGET_WORKER_HOST_UNAVAILABLE")]
    TargetWorkerHostUnavailable,
    #[serde(rename = "TARGET_WORKER_JOURNAL_CORRUPT")]
    TargetWorkerJournalCorrupt,
    #[serde(rename = "TARGET_WORKER_STATE_UNAVAILABLE")]
    TargetWorkerStateUnavailable,
    #[serde(rename = "TCP_CONNECT")]
    TcpConnect,
    #[serde(rename = "TLS_ALPN")]
    TlsAlpn,
    #[serde(rename = "TLS_CONNECT")]
    TlsConnect,
    #[serde(rename = "TLS_PROTOCOL")]
    TlsProtocol,
    #[serde(rename = "TLS_TIMEOUT")]
    TlsTimeout,
    #[serde(rename = "TRANSFORM_FAILED")]
    TransformFailed,
    #[serde(rename = "UNKNOWN_OPERATION")]
    UnknownOperation,
    #[serde(rename = "UNKNOWN_REQUEST")]
    UnknownRequest,
    #[serde(rename = "UNSUPPORTED_BROWSER_SYNTAX")]
    UnsupportedBrowserSyntax,
    #[serde(rename = "UNSUPPORTED_DIRECT_EVAL_BINDING")]
    UnsupportedDirectEvalBinding,
    #[serde(rename = "UNSUPPORTED_DIRECT_EVAL_SHAPE")]
    UnsupportedDirectEvalShape,
    #[serde(rename = "UNSUPPORTED_DYNAMIC_SCOPE")]
    UnsupportedDynamicScope,
    #[serde(rename = "UNSUPPORTED_IMPORT_SCRIPTS_SHAPE")]
    UnsupportedImportScriptsShape,
    #[serde(rename = "UPLOAD_QUEUE_FULL")]
    UploadQueueFull,
    #[serde(rename = "UPLOAD_READ_ERROR")]
    UploadReadError,
    #[serde(rename = "VIRTUAL_SERVICE_WORKER_FAILED")]
    VirtualServiceWorkerFailed,
    #[serde(rename = "WEBSOCKET_CLOSE_INVALID")]
    WebsocketCloseInvalid,
    #[serde(rename = "WEBSOCKET_MESSAGE_INVALID")]
    WebsocketMessageInvalid,
    #[serde(rename = "WEBSOCKET_PROTOCOL_INVALID")]
    WebsocketProtocolInvalid,
    #[serde(rename = "WEBSOCKET_SEND_QUEUE_FULL")]
    WebsocketSendQueueFull,
    #[serde(rename = "WEBSOCKET_SEQUENCE")]
    WebsocketSequence,
    #[serde(rename = "WEBSOCKET_STATE")]
    WebsocketState,
    #[serde(rename = "WEBSOCKET_TERMINAL")]
    WebsocketTerminal,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ErrorSpecification {
    pub stages: &'static [ErrorStage],
    pub retryable: bool,
    pub message_key: &'static str,
}

pub fn specification(code: ErrorCode) -> ErrorSpecification {
    match code {
        ErrorCode::AbiIdentifierCollision => ErrorSpecification {
            stages: &[ErrorStage::RewriteJs],
            retryable: false,
            message_key: "rewrite_js_blocked",
        },
        ErrorCode::AbiVersionMismatch => ErrorSpecification {
            stages: &[ErrorStage::RewriteJs],
            retryable: false,
            message_key: "rewrite_js_version_mismatch",
        },
        ErrorCode::BodyChunkEmpty => ErrorSpecification {
            stages: &[ErrorStage::Body],
            retryable: false,
            message_key: "body_invalid",
        },
        ErrorCode::BodyChunkInvalid => ErrorSpecification {
            stages: &[ErrorStage::Body],
            retryable: false,
            message_key: "body_invalid",
        },
        ErrorCode::BodyChunkLimit => ErrorSpecification {
            stages: &[ErrorStage::Body],
            retryable: false,
            message_key: "body_limit",
        },
        ErrorCode::BodySequence => ErrorSpecification {
            stages: &[ErrorStage::Body],
            retryable: false,
            message_key: "body_sequence_invalid",
        },
        ErrorCode::BootstrapFailed => ErrorSpecification {
            stages: &[ErrorStage::Bootstrap],
            retryable: false,
            message_key: "bootstrap_failed",
        },
        ErrorCode::BootstrapStateViolation => ErrorSpecification {
            stages: &[ErrorStage::Bootstrap],
            retryable: false,
            message_key: "bootstrap_failed",
        },
        ErrorCode::BrowserUnsupported => ErrorSpecification {
            stages: &[ErrorStage::Bootstrap],
            retryable: false,
            message_key: "browser_unsupported",
        },
        ErrorCode::Canceled => ErrorSpecification {
            stages: &[ErrorStage::Body],
            retryable: false,
            message_key: "request_canceled",
        },
        ErrorCode::CancelCode => ErrorSpecification {
            stages: &[ErrorStage::Body],
            retryable: false,
            message_key: "body_cancel_invalid",
        },
        ErrorCode::CancelSequence => ErrorSpecification {
            stages: &[ErrorStage::Body],
            retryable: false,
            message_key: "body_sequence_invalid",
        },
        ErrorCode::CapabilityRejected => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "capability_rejected",
        },
        ErrorCode::ClientAbort => ErrorSpecification {
            stages: &[ErrorStage::Socks, ErrorStage::Tls, ErrorStage::Http],
            retryable: false,
            message_key: "request_canceled",
        },
        ErrorCode::CodegenFailed => ErrorSpecification {
            stages: &[ErrorStage::RewriteJs],
            retryable: false,
            message_key: "rewrite_js_failed",
        },
        ErrorCode::ConnectTimeout => ErrorSpecification {
            stages: &[ErrorStage::Socks],
            retryable: true,
            message_key: "target_connect_timeout",
        },
        ErrorCode::ControlOriginRejected => ErrorSpecification {
            stages: &[ErrorStage::Bootstrap],
            retryable: false,
            message_key: "control_origin_rejected",
        },
        ErrorCode::ControlOriginUnavailable => ErrorSpecification {
            stages: &[ErrorStage::Bootstrap],
            retryable: true,
            message_key: "control_origin_unavailable",
        },
        ErrorCode::CookieContextInvalid => ErrorSpecification {
            stages: &[ErrorStage::Policy, ErrorStage::Cookie],
            retryable: false,
            message_key: "cookie_context_invalid",
        },
        ErrorCode::CookieCoreRejected => ErrorSpecification {
            stages: &[ErrorStage::Cookie],
            retryable: false,
            message_key: "cookie_update_rejected",
        },
        ErrorCode::CookieCoreUnavailable => ErrorSpecification {
            stages: &[ErrorStage::Cookie],
            retryable: false,
            message_key: "cookie_service_unavailable",
        },
        ErrorCode::CookieSequenceStale => ErrorSpecification {
            stages: &[ErrorStage::Policy, ErrorStage::Cookie],
            retryable: false,
            message_key: "cookie_sequence_stale",
        },
        ErrorCode::CookieStateCorrupt => ErrorSpecification {
            stages: &[ErrorStage::Cookie],
            retryable: false,
            message_key: "cookie_state_invalid",
        },
        ErrorCode::CookieStateUnavailable => ErrorSpecification {
            stages: &[ErrorStage::Cookie],
            retryable: true,
            message_key: "cookie_service_unavailable",
        },
        ErrorCode::CoordinatorFailed => ErrorSpecification {
            stages: &[ErrorStage::Coordinator],
            retryable: false,
            message_key: "coordinator_failed",
        },
        ErrorCode::CoordinatorRevisionCorrupt => ErrorSpecification {
            stages: &[ErrorStage::Coordinator],
            retryable: false,
            message_key: "coordinator_state_invalid",
        },
        ErrorCode::CoordinatorUnavailable => ErrorSpecification {
            stages: &[ErrorStage::Coordinator],
            retryable: true,
            message_key: "coordinator_unavailable",
        },
        ErrorCode::CorsFailed => ErrorSpecification {
            stages: &[ErrorStage::Cors],
            retryable: false,
            message_key: "network_request_failed",
        },
        ErrorCode::CredentialsModeInvalid => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "request_policy_blocked",
        },
        ErrorCode::CssRewriteFailed => ErrorSpecification {
            stages: &[ErrorStage::RewriteCss],
            retryable: false,
            message_key: "rewrite_css_failed",
        },
        ErrorCode::DnsResolution => ErrorSpecification {
            stages: &[ErrorStage::Socks],
            retryable: true,
            message_key: "target_dns_failed",
        },
        ErrorCode::DocumentCspInvalid => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "target_policy_blocked",
        },
        ErrorCode::DocumentEncodingUnsupported => ErrorSpecification {
            stages: &[ErrorStage::RewriteHtml],
            retryable: false,
            message_key: "rewrite_html_failed",
        },
        ErrorCode::DocumentRouteRejected => ErrorSpecification {
            stages: &[ErrorStage::Route],
            retryable: false,
            message_key: "route_invalid",
        },
        ErrorCode::DownloadBackpressure => ErrorSpecification {
            stages: &[ErrorStage::Body],
            retryable: false,
            message_key: "body_backpressure",
        },
        ErrorCode::DownloadChunkLimit => ErrorSpecification {
            stages: &[ErrorStage::Body],
            retryable: false,
            message_key: "body_limit",
        },
        ErrorCode::DownloadSequence => ErrorSpecification {
            stages: &[ErrorStage::Body],
            retryable: false,
            message_key: "body_sequence_invalid",
        },
        ErrorCode::DuplicateOperation => ErrorSpecification {
            stages: &[ErrorStage::Coordinator],
            retryable: false,
            message_key: "duplicate_operation",
        },
        ErrorCode::ErrorCode => ErrorSpecification {
            stages: &[ErrorStage::Body],
            retryable: false,
            message_key: "body_error_invalid",
        },
        ErrorCode::ErrorSequence => ErrorSpecification {
            stages: &[ErrorStage::Body],
            retryable: false,
            message_key: "body_sequence_invalid",
        },
        ErrorCode::EventDelivery => ErrorSpecification {
            stages: &[ErrorStage::Body],
            retryable: false,
            message_key: "body_delivery_failed",
        },
        ErrorCode::FailurePageAssetMissing => ErrorSpecification {
            stages: &[ErrorStage::RuntimeInstall],
            retryable: false,
            message_key: "runtime_install_failed",
        },
        ErrorCode::ForbiddenHeader => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "request_policy_blocked",
        },
        ErrorCode::FrameType => ErrorSpecification {
            stages: &[ErrorStage::Body],
            retryable: false,
            message_key: "body_frame_invalid",
        },
        ErrorCode::HandoffRejected => ErrorSpecification {
            stages: &[ErrorStage::Bootstrap],
            retryable: false,
            message_key: "handoff_rejected",
        },
        ErrorCode::HeaderInvalid => ErrorSpecification {
            stages: &[ErrorStage::Http],
            retryable: false,
            message_key: "http_header_invalid",
        },
        ErrorCode::HeaderLimit => ErrorSpecification {
            stages: &[ErrorStage::Http],
            retryable: false,
            message_key: "http_header_limit",
        },
        ErrorCode::HistoryRouteFailed => ErrorSpecification {
            stages: &[ErrorStage::Route],
            retryable: true,
            message_key: "route_expired",
        },
        ErrorCode::HostBindingRejected => ErrorSpecification {
            stages: &[ErrorStage::Bootstrap],
            retryable: false,
            message_key: "host_binding_rejected",
        },
        ErrorCode::HostConfigurationRejected => ErrorSpecification {
            stages: &[ErrorStage::Bootstrap],
            retryable: false,
            message_key: "host_configuration_rejected",
        },
        ErrorCode::HostConfigurationTimeout => ErrorSpecification {
            stages: &[ErrorStage::Bootstrap],
            retryable: true,
            message_key: "host_configuration_timeout",
        },
        ErrorCode::HostContextRejected => ErrorSpecification {
            stages: &[ErrorStage::Bootstrap],
            retryable: false,
            message_key: "host_context_rejected",
        },
        ErrorCode::HtmlRewriteFailed => ErrorSpecification {
            stages: &[ErrorStage::RewriteHtml],
            retryable: false,
            message_key: "rewrite_html_failed",
        },
        ErrorCode::HttpParse => ErrorSpecification {
            stages: &[ErrorStage::Http],
            retryable: false,
            message_key: "http_response_invalid",
        },
        ErrorCode::HttpTimeout => ErrorSpecification {
            stages: &[ErrorStage::Http],
            retryable: true,
            message_key: "http_timeout",
        },
        ErrorCode::ImportMapInvalid => ErrorSpecification {
            stages: &[ErrorStage::ImportMap],
            retryable: false,
            message_key: "import_map_invalid",
        },
        ErrorCode::InternalFailed => ErrorSpecification {
            stages: &[ErrorStage::Internal],
            retryable: false,
            message_key: "internal_failed",
        },
        ErrorCode::InvalidAddress => ErrorSpecification {
            stages: &[ErrorStage::ImportMap],
            retryable: false,
            message_key: "import_map_invalid",
        },
        ErrorCode::InvalidMessage => ErrorSpecification {
            stages: &[ErrorStage::Coordinator],
            retryable: false,
            message_key: "invalid_message",
        },
        ErrorCode::InvalidScope => ErrorSpecification {
            stages: &[ErrorStage::ImportMap],
            retryable: false,
            message_key: "import_map_invalid",
        },
        ErrorCode::InvalidSourceKind => ErrorSpecification {
            stages: &[ErrorStage::RewriteJs],
            retryable: false,
            message_key: "rewrite_js_source_invalid",
        },
        ErrorCode::InvalidSpecifierKey => ErrorSpecification {
            stages: &[ErrorStage::ImportMap],
            retryable: false,
            message_key: "import_map_invalid",
        },
        ErrorCode::KernelId => ErrorSpecification {
            stages: &[ErrorStage::Internal],
            retryable: false,
            message_key: "internal_protocol_invalid",
        },
        ErrorCode::MessageSchema => ErrorSpecification {
            stages: &[ErrorStage::Internal],
            retryable: false,
            message_key: "internal_protocol_invalid",
        },
        ErrorCode::MessageVersion => ErrorSpecification {
            stages: &[ErrorStage::Internal],
            retryable: false,
            message_key: "internal_version_mismatch",
        },
        ErrorCode::OriginInvalid => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "request_policy_blocked",
        },
        ErrorCode::ParseFailed => ErrorSpecification {
            stages: &[ErrorStage::RewriteJs],
            retryable: false,
            message_key: "rewrite_js_syntax_invalid",
        },
        ErrorCode::PersonaBinding => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "request_policy_blocked",
        },
        ErrorCode::PlanContextInvalid => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "request_policy_blocked",
        },
        ErrorCode::PlanIdInvalid => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "request_policy_blocked",
        },
        ErrorCode::PlanReplay => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "request_replay_blocked",
        },
        ErrorCode::PolicyBlocked => ErrorSpecification {
            stages: &[ErrorStage::Policy, ErrorStage::RewriteJs],
            retryable: false,
            message_key: "request_policy_blocked",
        },
        ErrorCode::PolicyDenied => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "request_policy_blocked",
        },
        ErrorCode::PortRequestLimit => ErrorSpecification {
            stages: &[ErrorStage::Coordinator],
            retryable: false,
            message_key: "coordinator_request_limit",
        },
        ErrorCode::PullLimit => ErrorSpecification {
            stages: &[ErrorStage::Body],
            retryable: false,
            message_key: "body_limit",
        },
        ErrorCode::PullOutstanding => ErrorSpecification {
            stages: &[ErrorStage::Body],
            retryable: false,
            message_key: "body_sequence_invalid",
        },
        ErrorCode::RelayCapabilityProfileMismatch => ErrorSpecification {
            stages: &[ErrorStage::Relay],
            retryable: false,
            message_key: "relay_profile_invalid",
        },
        ErrorCode::RelayLost => ErrorSpecification {
            stages: &[ErrorStage::Relay],
            retryable: true,
            message_key: "relay_connection_lost",
        },
        ErrorCode::RelayLostUnsafe => ErrorSpecification {
            stages: &[ErrorStage::Relay],
            retryable: false,
            message_key: "relay_connection_lost",
        },
        ErrorCode::RelayProfileConfigUnavailable => ErrorSpecification {
            stages: &[ErrorStage::Relay],
            retryable: false,
            message_key: "relay_profile_unavailable",
        },
        ErrorCode::RelayProfileNotInstalled => ErrorSpecification {
            stages: &[ErrorStage::Relay],
            retryable: false,
            message_key: "relay_profile_unavailable",
        },
        ErrorCode::RelayProfileSetMismatch => ErrorSpecification {
            stages: &[ErrorStage::Relay],
            retryable: false,
            message_key: "relay_profile_invalid",
        },
        ErrorCode::RelayUnavailable => ErrorSpecification {
            stages: &[ErrorStage::Relay],
            retryable: true,
            message_key: "relay_unavailable",
        },
        ErrorCode::ReleaseGateFailed => ErrorSpecification {
            stages: &[ErrorStage::Internal],
            retryable: false,
            message_key: "release_gate_failed",
        },
        ErrorCode::ReplayDetected => ErrorSpecification {
            stages: &[ErrorStage::Coordinator],
            retryable: false,
            message_key: "replay_detected",
        },
        ErrorCode::RequestBinding => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "request_policy_blocked",
        },
        ErrorCode::RequestContextInvalid => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "request_policy_blocked",
        },
        ErrorCode::RequestFailed => ErrorSpecification {
            stages: &[ErrorStage::Internal],
            retryable: false,
            message_key: "internal_failed",
        },
        ErrorCode::RequestIdInvalid => ErrorSpecification {
            stages: &[ErrorStage::Internal],
            retryable: false,
            message_key: "internal_protocol_invalid",
        },
        ErrorCode::RequestIdReplay => ErrorSpecification {
            stages: &[ErrorStage::Internal],
            retryable: false,
            message_key: "internal_replay_detected",
        },
        ErrorCode::RequestNotActive => ErrorSpecification {
            stages: &[ErrorStage::Internal],
            retryable: false,
            message_key: "internal_request_inactive",
        },
        ErrorCode::RequestTerminal => ErrorSpecification {
            stages: &[ErrorStage::Http, ErrorStage::Body],
            retryable: false,
            message_key: "request_already_finished",
        },
        ErrorCode::ResolutionFailed => ErrorSpecification {
            stages: &[ErrorStage::RewriteJs],
            retryable: false,
            message_key: "rewrite_js_failed",
        },
        ErrorCode::ResourceTooLarge => ErrorSpecification {
            stages: &[
                ErrorStage::RewriteHtml,
                ErrorStage::RewriteJs,
                ErrorStage::RewriteCss,
                ErrorStage::ImportMap,
                ErrorStage::Body,
            ],
            retryable: false,
            message_key: "resource_too_large",
        },
        ErrorCode::ResponseBody => ErrorSpecification {
            stages: &[ErrorStage::Body],
            retryable: true,
            message_key: "response_body_failed",
        },
        ErrorCode::RewriteFailed => ErrorSpecification {
            stages: &[ErrorStage::RewriteHtml],
            retryable: false,
            message_key: "rewrite_html_failed",
        },
        ErrorCode::RouteClassMismatch => ErrorSpecification {
            stages: &[ErrorStage::Route],
            retryable: false,
            message_key: "route_invalid",
        },
        ErrorCode::RouteExpired => ErrorSpecification {
            stages: &[ErrorStage::Route],
            retryable: true,
            message_key: "route_expired",
        },
        ErrorCode::RouteInvalid => ErrorSpecification {
            stages: &[ErrorStage::Route],
            retryable: false,
            message_key: "route_invalid",
        },
        ErrorCode::RouteNotFound => ErrorSpecification {
            stages: &[ErrorStage::Route],
            retryable: false,
            message_key: "route_not_found",
        },
        ErrorCode::RouteUnavailable => ErrorSpecification {
            stages: &[ErrorStage::Route],
            retryable: true,
            message_key: "route_expired",
        },
        ErrorCode::RuntimeAssetMissing => ErrorSpecification {
            stages: &[ErrorStage::RuntimeInstall],
            retryable: false,
            message_key: "runtime_install_failed",
        },
        ErrorCode::RuntimeInstallFailed => ErrorSpecification {
            stages: &[ErrorStage::RuntimeInstall],
            retryable: false,
            message_key: "runtime_install_failed",
        },
        ErrorCode::ScriptKindInvalid => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "script_policy_blocked",
        },
        ErrorCode::SealedRoutePolicyDenied => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "request_policy_blocked",
        },
        ErrorCode::SealedRouteTargetFailed => ErrorSpecification {
            stages: &[ErrorStage::Http],
            retryable: true,
            message_key: "network_request_failed",
        },
        ErrorCode::ServerCloseFailed => ErrorSpecification {
            stages: &[ErrorStage::Smux, ErrorStage::Socks, ErrorStage::Websocket],
            retryable: false,
            message_key: "internal_failed",
        },
        ErrorCode::ServerFailed => ErrorSpecification {
            stages: &[ErrorStage::Bootstrap],
            retryable: false,
            message_key: "internal_failed",
        },
        ErrorCode::ServerHttpError => ErrorSpecification {
            stages: &[ErrorStage::Internal],
            retryable: false,
            message_key: "internal_failed",
        },
        ErrorCode::ServiceWorkerRejected => ErrorSpecification {
            stages: &[ErrorStage::Bootstrap],
            retryable: false,
            message_key: "service_worker_rejected",
        },
        ErrorCode::ServiceWorkerScopeRejected => ErrorSpecification {
            stages: &[ErrorStage::Bootstrap],
            retryable: false,
            message_key: "service_worker_rejected",
        },
        ErrorCode::ServiceWorkerTimeout => ErrorSpecification {
            stages: &[ErrorStage::Bootstrap],
            retryable: true,
            message_key: "service_worker_unavailable",
        },
        ErrorCode::ServiceWorkerUnavailable => ErrorSpecification {
            stages: &[ErrorStage::Bootstrap],
            retryable: true,
            message_key: "service_worker_unavailable",
        },
        ErrorCode::SmuxProtocol => ErrorSpecification {
            stages: &[ErrorStage::Smux],
            retryable: false,
            message_key: "relay_protocol_failed",
        },
        ErrorCode::SmuxStreamLimit => ErrorSpecification {
            stages: &[ErrorStage::Smux],
            retryable: true,
            message_key: "relay_stream_limit",
        },
        ErrorCode::SocksPolicy => ErrorSpecification {
            stages: &[ErrorStage::Socks],
            retryable: false,
            message_key: "target_policy_blocked",
        },
        ErrorCode::SocksProtocol => ErrorSpecification {
            stages: &[ErrorStage::Socks],
            retryable: false,
            message_key: "target_connect_failed",
        },
        ErrorCode::SocksReply => ErrorSpecification {
            stages: &[ErrorStage::Socks],
            retryable: true,
            message_key: "target_connect_failed",
        },
        ErrorCode::StaleOperation => ErrorSpecification {
            stages: &[ErrorStage::Coordinator],
            retryable: true,
            message_key: "stale_operation",
        },
        ErrorCode::StorageFailed => ErrorSpecification {
            stages: &[ErrorStage::Storage],
            retryable: false,
            message_key: "storage_failed",
        },
        ErrorCode::StreamIdleTimeout => ErrorSpecification {
            stages: &[ErrorStage::Body],
            retryable: true,
            message_key: "body_timeout",
        },
        ErrorCode::StreamLimit => ErrorSpecification {
            stages: &[ErrorStage::Relay],
            retryable: true,
            message_key: "relay_stream_limit",
        },
        ErrorCode::StreamTotalTimeout => ErrorSpecification {
            stages: &[ErrorStage::Body],
            retryable: true,
            message_key: "body_timeout",
        },
        ErrorCode::TargetAddressPolicy => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "target_policy_blocked",
        },
        ErrorCode::TargetCertificate => ErrorSpecification {
            stages: &[ErrorStage::Tls],
            retryable: false,
            message_key: "target_certificate_failed",
        },
        ErrorCode::TargetCoepBlocked => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "target_policy_blocked",
        },
        ErrorCode::TargetCspBlocked => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "target_policy_blocked",
        },
        ErrorCode::TargetCspInvalid => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "target_policy_blocked",
        },
        ErrorCode::TargetDocumentPolicyInvalid => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "target_policy_blocked",
        },
        ErrorCode::TargetFetchFailed => ErrorSpecification {
            stages: &[ErrorStage::Http],
            retryable: true,
            message_key: "network_request_failed",
        },
        ErrorCode::TargetFramePolicyBlocked => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "target_policy_blocked",
        },
        ErrorCode::TargetPortBlocked => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "target_port_blocked",
        },
        ErrorCode::TargetUrl => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "target_url_invalid",
        },
        ErrorCode::TargetUrlInvalid => ErrorSpecification {
            stages: &[ErrorStage::Policy],
            retryable: false,
            message_key: "target_url_invalid",
        },
        ErrorCode::TargetWorkerFetchFailed => ErrorSpecification {
            stages: &[ErrorStage::VirtualServiceWorker],
            retryable: true,
            message_key: "virtual_service_worker_unavailable",
        },
        ErrorCode::TargetWorkerHostRejected => ErrorSpecification {
            stages: &[ErrorStage::VirtualServiceWorker],
            retryable: false,
            message_key: "virtual_service_worker_failed",
        },
        ErrorCode::TargetWorkerHostUnavailable => ErrorSpecification {
            stages: &[ErrorStage::VirtualServiceWorker],
            retryable: true,
            message_key: "virtual_service_worker_unavailable",
        },
        ErrorCode::TargetWorkerJournalCorrupt => ErrorSpecification {
            stages: &[ErrorStage::VirtualServiceWorker],
            retryable: false,
            message_key: "virtual_service_worker_state_invalid",
        },
        ErrorCode::TargetWorkerStateUnavailable => ErrorSpecification {
            stages: &[ErrorStage::VirtualServiceWorker],
            retryable: true,
            message_key: "virtual_service_worker_unavailable",
        },
        ErrorCode::TcpConnect => ErrorSpecification {
            stages: &[ErrorStage::Socks],
            retryable: true,
            message_key: "target_connect_failed",
        },
        ErrorCode::TlsAlpn => ErrorSpecification {
            stages: &[ErrorStage::Tls],
            retryable: false,
            message_key: "target_tls_failed",
        },
        ErrorCode::TlsConnect => ErrorSpecification {
            stages: &[ErrorStage::Tls],
            retryable: false,
            message_key: "target_tls_failed",
        },
        ErrorCode::TlsProtocol => ErrorSpecification {
            stages: &[ErrorStage::Tls],
            retryable: false,
            message_key: "target_tls_failed",
        },
        ErrorCode::TlsTimeout => ErrorSpecification {
            stages: &[ErrorStage::Tls],
            retryable: true,
            message_key: "target_tls_timeout",
        },
        ErrorCode::TransformFailed => ErrorSpecification {
            stages: &[ErrorStage::RewriteJs],
            retryable: false,
            message_key: "rewrite_js_failed",
        },
        ErrorCode::UnknownOperation => ErrorSpecification {
            stages: &[ErrorStage::Coordinator],
            retryable: false,
            message_key: "unknown_operation",
        },
        ErrorCode::UnknownRequest => ErrorSpecification {
            stages: &[ErrorStage::Route],
            retryable: false,
            message_key: "route_invalid",
        },
        ErrorCode::UnsupportedBrowserSyntax => ErrorSpecification {
            stages: &[ErrorStage::RewriteJs],
            retryable: false,
            message_key: "rewrite_js_syntax_unsupported",
        },
        ErrorCode::UnsupportedDirectEvalBinding => ErrorSpecification {
            stages: &[ErrorStage::RewriteJs],
            retryable: false,
            message_key: "rewrite_js_policy_blocked",
        },
        ErrorCode::UnsupportedDirectEvalShape => ErrorSpecification {
            stages: &[ErrorStage::RewriteJs],
            retryable: false,
            message_key: "rewrite_js_policy_blocked",
        },
        ErrorCode::UnsupportedDynamicScope => ErrorSpecification {
            stages: &[ErrorStage::RewriteJs],
            retryable: false,
            message_key: "rewrite_js_policy_blocked",
        },
        ErrorCode::UnsupportedImportScriptsShape => ErrorSpecification {
            stages: &[ErrorStage::RewriteJs],
            retryable: false,
            message_key: "rewrite_js_policy_blocked",
        },
        ErrorCode::UploadQueueFull => ErrorSpecification {
            stages: &[ErrorStage::Body],
            retryable: true,
            message_key: "body_backpressure",
        },
        ErrorCode::UploadReadError => ErrorSpecification {
            stages: &[ErrorStage::Body],
            retryable: false,
            message_key: "body_upload_failed",
        },
        ErrorCode::VirtualServiceWorkerFailed => ErrorSpecification {
            stages: &[ErrorStage::VirtualServiceWorker],
            retryable: false,
            message_key: "virtual_service_worker_failed",
        },
        ErrorCode::WebsocketCloseInvalid => ErrorSpecification {
            stages: &[ErrorStage::Websocket],
            retryable: false,
            message_key: "websocket_protocol_invalid",
        },
        ErrorCode::WebsocketMessageInvalid => ErrorSpecification {
            stages: &[ErrorStage::Websocket],
            retryable: false,
            message_key: "websocket_protocol_invalid",
        },
        ErrorCode::WebsocketProtocolInvalid => ErrorSpecification {
            stages: &[ErrorStage::Websocket],
            retryable: false,
            message_key: "websocket_protocol_invalid",
        },
        ErrorCode::WebsocketSendQueueFull => ErrorSpecification {
            stages: &[ErrorStage::Websocket],
            retryable: true,
            message_key: "websocket_backpressure",
        },
        ErrorCode::WebsocketSequence => ErrorSpecification {
            stages: &[ErrorStage::Websocket],
            retryable: false,
            message_key: "websocket_protocol_invalid",
        },
        ErrorCode::WebsocketState => ErrorSpecification {
            stages: &[ErrorStage::Websocket],
            retryable: false,
            message_key: "websocket_failed",
        },
        ErrorCode::WebsocketTerminal => ErrorSpecification {
            stages: &[ErrorStage::Websocket],
            retryable: false,
            message_key: "websocket_failed",
        },
    }
}

#[derive(Debug, Eq, PartialEq)]
pub enum AuthorityError {
    UnknownVersion(u16),
    InvalidStage,
    InvalidRetryable,
    InvalidRequestId,
    InvalidEnvelope(String),
    InvalidMessageKey,
}

impl fmt::Display for AuthorityError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::UnknownVersion(version) => write!(formatter, "unknown error version {version}"),
            Self::InvalidStage => formatter.write_str("invalid error stage"),
            Self::InvalidRetryable => formatter.write_str("invalid retryable value"),
            Self::InvalidRequestId => formatter.write_str("invalid request ID"),
            Self::InvalidEnvelope(message) => {
                write!(formatter, "invalid error envelope: {message}")
            }
            Self::InvalidMessageKey => formatter.write_str("invalid public message key"),
        }
    }
}

impl std::error::Error for AuthorityError {}

#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct InternalError {
    pub code: ErrorCode,
    pub stage: ErrorStage,
    pub retryable: bool,
    pub request_id: String,
    pub internal_cause: Value,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct PublicError {
    pub code: ErrorCode,
    pub stage: ErrorStage,
    pub retryable: bool,
    pub request_id: String,
    pub message_key: String,
}

fn validate_version(error_version: u16) -> Result<(), AuthorityError> {
    if error_version != ERROR_VERSION {
        return Err(AuthorityError::UnknownVersion(error_version));
    }
    Ok(())
}

fn valid_request_id(value: &str) -> bool {
    (16..=64).contains(&value.len())
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-'))
}

fn validate_common(
    code: ErrorCode,
    stage: ErrorStage,
    retryable: bool,
    request_id: &str,
) -> Result<ErrorSpecification, AuthorityError> {
    let specification = specification(code);
    if !specification.stages.contains(&stage) {
        return Err(AuthorityError::InvalidStage);
    }
    if retryable != specification.retryable {
        return Err(AuthorityError::InvalidRetryable);
    }
    if !valid_request_id(request_id) {
        return Err(AuthorityError::InvalidRequestId);
    }
    Ok(specification)
}

impl InternalError {
    pub fn new(
        error_version: u16,
        code: ErrorCode,
        stage: ErrorStage,
        request_id: impl Into<String>,
        internal_cause: Value,
    ) -> Result<Self, AuthorityError> {
        validate_version(error_version)?;
        let request_id = request_id.into();
        let specification =
            validate_common(code, stage, specification(code).retryable, &request_id)?;
        Ok(Self {
            code,
            stage,
            retryable: specification.retryable,
            request_id,
            internal_cause,
        })
    }

    pub fn validate(&self, error_version: u16) -> Result<(), AuthorityError> {
        validate_version(error_version)?;
        validate_common(self.code, self.stage, self.retryable, &self.request_id)?;
        Ok(())
    }

    pub fn public(&self, error_version: u16) -> Result<PublicError, AuthorityError> {
        self.validate(error_version)?;
        let specification = specification(self.code);
        Ok(PublicError {
            code: self.code,
            stage: self.stage,
            retryable: self.retryable,
            request_id: self.request_id.clone(),
            message_key: specification.message_key.to_owned(),
        })
    }
}

impl PublicError {
    pub fn validate(&self, error_version: u16) -> Result<(), AuthorityError> {
        validate_version(error_version)?;
        let specification =
            validate_common(self.code, self.stage, self.retryable, &self.request_id)?;
        if self.message_key != specification.message_key {
            return Err(AuthorityError::InvalidMessageKey);
        }
        Ok(())
    }
}

pub fn decode_internal(error_version: u16, encoded: &str) -> Result<InternalError, AuthorityError> {
    let value: InternalError = serde_json::from_str(encoded)
        .map_err(|error| AuthorityError::InvalidEnvelope(error.to_string()))?;
    value.validate(error_version)?;
    Ok(value)
}

pub fn decode_public(error_version: u16, encoded: &str) -> Result<PublicError, AuthorityError> {
    let value: PublicError = serde_json::from_str(encoded)
        .map_err(|error| AuthorityError::InvalidEnvelope(error.to_string()))?;
    value.validate(error_version)?;
    Ok(value)
}
