[package]
name="html-rewriter"
version.workspace=true
edition.workspace=true
license.workspace=true
[lib]
crate-type=["cdylib","rlib"]
[dependencies]
base64="0.22.1"
lol_html="3.0.0"
html5gum="0.8.4"
policy-core={path="../policy-core"}
thiserror.workspace=true
parking_lot="0.12.5"
wasm-bindgen.workspace=true
js-sys="0.3.99"
serde_json.workspace=true
serde.workspace=true
css-rewriter={path="../css-rewriter"}
js-compiler={path="../js-compiler"}
[dev-dependencies]
