[package]
name="share-crypto"
version.workspace=true
edition.workspace=true
license.workspace=true
[lib]
crate-type=["cdylib","rlib"]
[dependencies]
aes-gcm="0.10.3"
base64="0.22.1"
minicbor={version="2.1.1",features=["derive","std"]}
rand="0.9.1"
getrandom03={package="getrandom",version="0.3.4",features=["wasm_js"]}
getrandom.workspace=true
serde.workspace=true
thiserror.workspace=true
sha2="0.10.9"
wasm-bindgen.workspace=true
url.workspace=true
