import { execFileSync } from "node:child_process";
import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const sourcePath = path.join(root, "protocol/errors.sources.json");
const outputs = Object.freeze({
  schema: path.join(root, "protocol/errors.schema.json"),
  javascript: path.join(root, "web/generated/errors.mjs"),
  go: path.join(root, "internal/errorauthority/generated.go"),
  rust: path.join(root, "crates/error-authority/src/lib.rs"),
});
const mode = process.argv[2] ?? "";
if (!["", "--check"].includes(mode)) throw new Error("usage: generate-errors.mjs [--check]");

const requiredStages = Object.freeze([
  "BOOTSTRAP",
  "COORDINATOR",
  "ROUTE",
  "POLICY",
  "REWRITE_HTML",
  "REWRITE_JS",
  "REWRITE_CSS",
  "IMPORT_MAP",
  "RUNTIME_INSTALL",
  "RELAY",
  "SMUX",
  "SOCKS",
  "TLS",
  "HTTP",
  "CORS",
  "BODY",
  "WEBSOCKET",
  "COOKIE",
  "STORAGE",
  "VIRTUAL_SERVICE_WORKER",
  "INTERNAL",
]);
const source = JSON.parse(await readFile(sourcePath, "utf8"));
const codePattern = /^[A-Z][A-Z0-9_]{1,63}$/u;
const messageKeyPattern = /^[a-z][a-z0-9_]{1,63}$/u;
const stageOrder = new Map(requiredStages.map((stage, index) => [stage, index]));

if (source.schema_version !== 1 || source.error_version !== 2) throw new Error("invalid error authority version");
if (JSON.stringify(source.stages) !== JSON.stringify(requiredStages)) throw new Error("error stages do not match the required closed order");
if (!Array.isArray(source.codes) || source.codes.length === 0) throw new Error("error authority has no codes");
const codeNames = source.codes.map(({ code }) => code);
if (JSON.stringify(codeNames) !== JSON.stringify([...codeNames].sort()) || new Set(codeNames).size !== codeNames.length) {
  throw new Error("error codes must be sorted and unique");
}
for (const entry of source.codes) {
  const keys = Object.keys(entry).sort();
  if (JSON.stringify(keys) !== JSON.stringify(["code", "message_key", "retryable", "stages"])) throw new Error(`invalid error entry shape ${entry.code ?? "<missing>"}`);
  if (!codePattern.test(entry.code) || typeof entry.retryable !== "boolean" || !messageKeyPattern.test(entry.message_key)) throw new Error(`invalid error entry ${entry.code ?? "<missing>"}`);
  if (!Array.isArray(entry.stages) || entry.stages.length === 0 || new Set(entry.stages).size !== entry.stages.length) throw new Error(`invalid stages for ${entry.code}`);
  if (entry.stages.some(stage => !stageOrder.has(stage))) throw new Error(`unknown stage for ${entry.code}`);
  const ordered = [...entry.stages].sort((left, right) => stageOrder.get(left) - stageOrder.get(right));
  if (JSON.stringify(ordered) !== JSON.stringify(entry.stages)) throw new Error(`stages must follow authority order for ${entry.code}`);
}
for (const stage of requiredStages) {
  if (!source.codes.some(entry => entry.stages.includes(stage))) throw new Error(`error stage has no registered code: ${stage}`);
}

function variants(kind) {
  const publicError = kind === "public";
  return source.codes.flatMap(entry => entry.stages.map(stage => ({
    type: "object",
    additionalProperties: false,
    required: publicError
      ? ["code", "stage", "retryable", "request_id", "message_key"]
      : ["code", "stage", "retryable", "request_id", "internal_cause"],
    properties: {
      code: { const: entry.code },
      stage: { const: stage },
      retryable: { const: entry.retryable },
      request_id: { $ref: "#/$defs/request_id" },
      ...(publicError
        ? { message_key: { const: entry.message_key } }
        : { internal_cause: {} }),
    },
  })));
}

function schemaSource() {
  const schema = {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    $id: "https://zeroproxy.invalid/protocol/errors.schema.json",
    $ref: "#/$defs/public_error",
    $defs: {
      error_version: { const: source.error_version },
      code: { enum: codeNames },
      stage: { enum: requiredStages },
      request_id: {
        type: "string",
        minLength: 16,
        maxLength: 64,
        pattern: "^[A-Za-z0-9_-]+$",
      },
      internal_error: { oneOf: variants("internal") },
      public_error: { oneOf: variants("public") },
    },
  };
  return `${JSON.stringify(schema, null, 2)}\n`;
}

function javascriptSource() {
  const specifications = Object.fromEntries(source.codes.map(entry => [entry.code, {
    stages: entry.stages,
    retryable: entry.retryable,
    message_key: entry.message_key,
  }]));
  return `// Generated by scripts/generate-errors.mjs. DO NOT EDIT.\nexport const ERROR_SCHEMA_VERSION = ${source.schema_version};\nexport const ERROR_VERSION = ${source.error_version};\nexport const ERROR_STAGES = Object.freeze(${JSON.stringify(requiredStages)});\nexport const ERROR_CODES = Object.freeze(${JSON.stringify(codeNames)});\nconst specifications = Object.freeze(Object.fromEntries(Object.entries(${JSON.stringify(specifications)}).map(([code, specification]) => [code, Object.freeze({...specification, stages:Object.freeze(specification.stages)})])));\nconst requestIDPattern = /^[A-Za-z0-9_-]{16,64}$/u;\n\nfunction exactObject(value, keys) {\n  return value !== null\n    && typeof value === \"object\"\n    && !Array.isArray(value)\n    && Object.keys(value).length === keys.length\n    && keys.every(key => Object.hasOwn(value, key));\n}\n\nfunction validJSONValue(value, ancestors = new Set()) {\n  if (value === null || typeof value === \"string\" || typeof value === \"boolean\") return true;\n  if (typeof value === \"number\") return Number.isFinite(value);\n  if (typeof value !== \"object\" || ancestors.has(value)) return false;\n  if (!Array.isArray(value) && ![Object.prototype, null].includes(Object.getPrototypeOf(value))) return false;\n  ancestors.add(value);\n  const valid = (Array.isArray(value) ? value : Object.values(value))\n    .every(item => validJSONValue(item, ancestors));\n  ancestors.delete(value);\n  return valid;\n}\n\nfunction specification(code) {\n  const value = specifications[code];\n  if (!value) throw new TypeError(\"unknown error code\");\n  return value;\n}\n\nfunction validateVersion(errorVersion) {\n  if (errorVersion !== ERROR_VERSION) throw new TypeError(\"unknown error version\");\n}\n\nfunction validateCommon(value, specificationValue) {\n  if (!specificationValue.stages.includes(value.stage)) throw new TypeError(\"invalid error stage\");\n  if (value.retryable !== specificationValue.retryable) throw new TypeError(\"invalid retryable value\");\n  if (typeof value.request_id !== \"string\" || !requestIDPattern.test(value.request_id)) throw new TypeError(\"invalid error request ID\");\n}\n\nexport function errorSpecification(code) {\n  return specification(code);\n}\n\nexport function createInternalError(code, stage, requestID, internalCause, errorVersion = ERROR_VERSION) {\n  validateVersion(errorVersion);\n  const value = {code, stage, retryable: specification(code).retryable, request_id: requestID, internal_cause: internalCause};\n  return normalizeInternalError(value, errorVersion);\n}\n\nexport function normalizeInternalError(value, errorVersion = ERROR_VERSION) {\n  validateVersion(errorVersion);\n  if (!exactObject(value, [\"code\", \"stage\", \"retryable\", \"request_id\", \"internal_cause\"])) throw new TypeError(\"invalid internal error envelope\");\n  const specificationValue = specification(value.code);\n  validateCommon(value, specificationValue);\n  if (!validJSONValue(value.internal_cause)) throw new TypeError(\"invalid internal error cause\");\n  return Object.freeze({...value});\n}\n\nexport function createPublicError(code, requestID, stage = specification(code).stages[0], errorVersion = ERROR_VERSION) {\n  validateVersion(errorVersion);\n  const specificationValue = specification(code);\n  const value = {code, stage, retryable: specificationValue.retryable, request_id: requestID, message_key: specificationValue.message_key};\n  return normalizePublicError(value, errorVersion);\n}\n\nexport function publicizeError(value, errorVersion = ERROR_VERSION) {\n  const internal = normalizeInternalError(value, errorVersion);\n  return createPublicError(internal.code, internal.request_id, internal.stage, errorVersion);\n}\n\nexport function normalizePublicError(value, errorVersion = ERROR_VERSION) {\n  validateVersion(errorVersion);\n  if (!exactObject(value, [\"code\", \"stage\", \"retryable\", \"request_id\", \"message_key\"])) throw new TypeError(\"invalid public error envelope\");\n  const specificationValue = specification(value.code);\n  validateCommon(value, specificationValue);\n  if (value.message_key !== specificationValue.message_key) throw new TypeError(\"invalid public message key\");\n  return Object.freeze({...value});\n}\n`;
}

function pascal(value) {
  return value.toLowerCase().split("_").map(part => `${part[0].toUpperCase()}${part.slice(1)}`).join("");
}

function goSource() {
  const stageConstants = requiredStages.map(stage => `\tStage${pascal(stage)} ErrorStage = ${JSON.stringify(stage)}`).join("\n");
  const codeConstants = source.codes.map(({ code }) => `\tCode${pascal(code)} ErrorCode = ${JSON.stringify(code)}`).join("\n");
  const cases = source.codes.map(entry => `\tcase Code${pascal(entry.code)}:\n\t\treturn errorSpecification{stages: []ErrorStage{${entry.stages.map(stage => `Stage${pascal(stage)}`).join(", ")}}, retryable: ${entry.retryable}, messageKey: ${JSON.stringify(entry.message_key)}}, true`).join("\n");
  return `// Code generated by scripts/generate-errors.mjs. DO NOT EDIT.\npackage errorauthority\n\nimport (\n\t\"bytes\"\n\t\"encoding/json\"\n\t\"fmt\"\n\t\"io\"\n)\n\nconst (\n\tSchemaVersion = ${source.schema_version}\n\tErrorVersion = ${source.error_version}\n)\n\ntype ErrorStage string\ntype ErrorCode string\n\nconst (\n${stageConstants}\n)\n\nconst (\n${codeConstants}\n)\n\ntype errorSpecification struct {\n\tstages []ErrorStage\n\tretryable bool\n\tmessageKey string\n}\n\nfunc specification(code ErrorCode) (errorSpecification, bool) {\n\tswitch code {\n${cases}\n\tdefault:\n\t\treturn errorSpecification{}, false\n\t}\n}\n\ntype InternalError struct {\n\tCode ErrorCode \`json:\"code\"\`\n\tStage ErrorStage \`json:\"stage\"\`\n\tRetryable bool \`json:\"retryable\"\`\n\tRequestID string \`json:\"request_id\"\`\n\tInternalCause any \`json:\"internal_cause\"\`\n}\n\ntype PublicError struct {\n\tCode ErrorCode \`json:\"code\"\`\n\tStage ErrorStage \`json:\"stage\"\`\n\tRetryable bool \`json:\"retryable\"\`\n\tRequestID string \`json:\"request_id\"\`\n\tMessageKey string \`json:\"message_key\"\`\n}\n\nfunc validRequestID(value string) bool {\n\tif len(value) < 16 || len(value) > 64 {\n\t\treturn false\n\t}\n\tfor _, character := range value {\n\t\tif !((character >= 'a' && character <= 'z') || (character >= 'A' && character <= 'Z') || (character >= '0' && character <= '9') || character == '_' || character == '-') {\n\t\t\treturn false\n\t\t}\n\t}\n\treturn true\n}\n\nfunc validateVersion(errorVersion int) error {\n\tif errorVersion != ErrorVersion {\n\t\treturn fmt.Errorf(\"unknown error version %d\", errorVersion)\n\t}\n\treturn nil\n}\n\nfunc validateCommon(code ErrorCode, stage ErrorStage, retryable bool, requestID string) (errorSpecification, error) {\n\tspecificationValue, known := specification(code)\n\tif !known {\n\t\treturn errorSpecification{}, fmt.Errorf(\"unknown error code %q\", code)\n\t}\n\tstageAllowed := false\n\tfor _, allowed := range specificationValue.stages {\n\t\tstageAllowed = stageAllowed || allowed == stage\n\t}\n\tif !stageAllowed {\n\t\treturn errorSpecification{}, fmt.Errorf(\"invalid stage %q for error code %q\", stage, code)\n\t}\n\tif retryable != specificationValue.retryable {\n\t\treturn errorSpecification{}, fmt.Errorf(\"invalid retryable value for error code %q\", code)\n\t}\n\tif !validRequestID(requestID) {\n\t\treturn errorSpecification{}, fmt.Errorf(\"invalid request ID\")\n\t}\n\treturn specificationValue, nil\n}\n\nfunc NewInternal(errorVersion int, code ErrorCode, stage ErrorStage, requestID string, internalCause any) (InternalError, error) {\n\tif err := validateVersion(errorVersion); err != nil {\n\t\treturn InternalError{}, err\n\t}\n\tspecificationValue, err := validateCommon(code, stage, specificationRetryable(code), requestID)\n\tif err != nil {\n\t\treturn InternalError{}, err\n\t}\n\tif _, err := json.Marshal(internalCause); err != nil {\n\t\treturn InternalError{}, fmt.Errorf(\"invalid internal cause: %w\", err)\n\t}\n\treturn InternalError{Code: code, Stage: stage, Retryable: specificationValue.retryable, RequestID: requestID, InternalCause: internalCause}, nil\n}\n\nfunc specificationRetryable(code ErrorCode) bool {\n\tspecificationValue, known := specification(code)\n\treturn known && specificationValue.retryable\n}\n\nfunc (value InternalError) Validate(errorVersion int) error {\n\tif err := validateVersion(errorVersion); err != nil {\n\t\treturn err\n\t}\n\tif _, err := validateCommon(value.Code, value.Stage, value.Retryable, value.RequestID); err != nil {\n\t\treturn err\n\t}\n\tif _, err := json.Marshal(value.InternalCause); err != nil {\n\t\treturn fmt.Errorf(\"invalid internal cause: %w\", err)\n\t}\n\treturn nil\n}\n\nfunc (value InternalError) Public(errorVersion int) (PublicError, error) {\n\tif err := value.Validate(errorVersion); err != nil {\n\t\treturn PublicError{}, err\n\t}\n\tspecificationValue, _ := specification(value.Code)\n\treturn PublicError{Code: value.Code, Stage: value.Stage, Retryable: value.Retryable, RequestID: value.RequestID, MessageKey: specificationValue.messageKey}, nil\n}\n\nfunc (value PublicError) Validate(errorVersion int) error {\n\tif err := validateVersion(errorVersion); err != nil {\n\t\treturn err\n\t}\n\tspecificationValue, err := validateCommon(value.Code, value.Stage, value.Retryable, value.RequestID)\n\tif err != nil {\n\t\treturn err\n\t}\n\tif value.MessageKey != specificationValue.messageKey {\n\t\treturn fmt.Errorf(\"invalid message key for error code %q\", value.Code)\n\t}\n\treturn nil\n}\n\nfunc decodeExact(data []byte, destination any) error {\n\tdecoder := json.NewDecoder(bytes.NewReader(data))\n\tdecoder.DisallowUnknownFields()\n\tif err := decoder.Decode(destination); err != nil {\n\t\treturn err\n\t}\n\tif err := decoder.Decode(&struct{}{}); err != io.EOF {\n\t\treturn fmt.Errorf(\"trailing error envelope data\")\n\t}\n\treturn nil\n}\n\nfunc DecodeInternal(errorVersion int, data []byte) (InternalError, error) {\n\tvar value InternalError\n\tif err := decodeExact(data, &value); err != nil {\n\t\treturn InternalError{}, err\n\t}\n\treturn value, value.Validate(errorVersion)\n}\n\nfunc DecodePublic(errorVersion int, data []byte) (PublicError, error) {\n\tvar value PublicError\n\tif err := decodeExact(data, &value); err != nil {\n\t\treturn PublicError{}, err\n\t}\n\treturn value, value.Validate(errorVersion)\n}\n`;
}

function rustSource() {
  const stageVariants = requiredStages.map(stage => `    #[serde(rename = ${JSON.stringify(stage)})]\n    ${pascal(stage)},`).join("\n");
  const codeVariants = source.codes.map(({ code }) => `    #[serde(rename = ${JSON.stringify(code)})]\n    ${pascal(code)},`).join("\n");
  const cases = source.codes.map(entry => `        ErrorCode::${pascal(entry.code)} => ErrorSpecification { stages: &[${entry.stages.map(stage => `ErrorStage::${pascal(stage)}`).join(", ")}], retryable: ${entry.retryable}, message_key: ${JSON.stringify(entry.message_key)} },`).join("\n");
  return `// Generated by scripts/generate-errors.mjs. DO NOT EDIT.\nuse serde::{Deserialize, Serialize};\nuse serde_json::Value;\nuse std::fmt;\n\npub const ERROR_SCHEMA_VERSION: u16 = ${source.schema_version};\npub const ERROR_VERSION: u16 = ${source.error_version};\n\n#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]\npub enum ErrorStage {\n${stageVariants}\n}\n\n#[derive(Clone, Copy, Debug, Deserialize, Eq, PartialEq, Serialize)]\npub enum ErrorCode {\n${codeVariants}\n}\n\n#[derive(Clone, Copy, Debug, Eq, PartialEq)]\npub struct ErrorSpecification {\n    pub stages: &'static [ErrorStage],\n    pub retryable: bool,\n    pub message_key: &'static str,\n}\n\npub fn specification(code: ErrorCode) -> ErrorSpecification {\n    match code {\n${cases}\n    }\n}\n\n#[derive(Debug, Eq, PartialEq)]\npub enum AuthorityError {\n    UnknownVersion(u16),\n    InvalidStage,\n    InvalidRetryable,\n    InvalidRequestId,\n    InvalidEnvelope(String),\n    InvalidMessageKey,\n}\n\nimpl fmt::Display for AuthorityError {\n    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {\n        match self {\n            Self::UnknownVersion(version) => write!(formatter, \"unknown error version {version}\"),\n            Self::InvalidStage => formatter.write_str(\"invalid error stage\"),\n            Self::InvalidRetryable => formatter.write_str(\"invalid retryable value\"),\n            Self::InvalidRequestId => formatter.write_str(\"invalid request ID\"),\n            Self::InvalidEnvelope(message) => write!(formatter, \"invalid error envelope: {message}\"),\n            Self::InvalidMessageKey => formatter.write_str(\"invalid public message key\"),\n        }\n    }\n}\n\nimpl std::error::Error for AuthorityError {}\n\n#[derive(Clone, Debug, Deserialize, PartialEq, Serialize)]\n#[serde(deny_unknown_fields)]\npub struct InternalError {\n    pub code: ErrorCode,\n    pub stage: ErrorStage,\n    pub retryable: bool,\n    pub request_id: String,\n    pub internal_cause: Value,\n}\n\n#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]\n#[serde(deny_unknown_fields)]\npub struct PublicError {\n    pub code: ErrorCode,\n    pub stage: ErrorStage,\n    pub retryable: bool,\n    pub request_id: String,\n    pub message_key: String,\n}\n\nfn validate_version(error_version: u16) -> Result<(), AuthorityError> {\n    if error_version != ERROR_VERSION {\n        return Err(AuthorityError::UnknownVersion(error_version));\n    }\n    Ok(())\n}\n\nfn valid_request_id(value: &str) -> bool {\n    (16..=64).contains(&value.len())\n        && value.bytes().all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-'))\n}\n\nfn validate_common(code: ErrorCode, stage: ErrorStage, retryable: bool, request_id: &str) -> Result<ErrorSpecification, AuthorityError> {\n    let specification = specification(code);\n    if !specification.stages.contains(&stage) {\n        return Err(AuthorityError::InvalidStage);\n    }\n    if retryable != specification.retryable {\n        return Err(AuthorityError::InvalidRetryable);\n    }\n    if !valid_request_id(request_id) {\n        return Err(AuthorityError::InvalidRequestId);\n    }\n    Ok(specification)\n}\n\nimpl InternalError {\n    pub fn new(error_version: u16, code: ErrorCode, stage: ErrorStage, request_id: impl Into<String>, internal_cause: Value) -> Result<Self, AuthorityError> {\n        validate_version(error_version)?;\n        let request_id = request_id.into();\n        let specification = validate_common(code, stage, specification(code).retryable, &request_id)?;\n        Ok(Self { code, stage, retryable: specification.retryable, request_id, internal_cause })\n    }\n\n    pub fn validate(&self, error_version: u16) -> Result<(), AuthorityError> {\n        validate_version(error_version)?;\n        validate_common(self.code, self.stage, self.retryable, &self.request_id)?;\n        Ok(())\n    }\n\n    pub fn public(&self, error_version: u16) -> Result<PublicError, AuthorityError> {\n        self.validate(error_version)?;\n        let specification = specification(self.code);\n        Ok(PublicError { code: self.code, stage: self.stage, retryable: self.retryable, request_id: self.request_id.clone(), message_key: specification.message_key.to_owned() })\n    }\n}\n\nimpl PublicError {\n    pub fn validate(&self, error_version: u16) -> Result<(), AuthorityError> {\n        validate_version(error_version)?;\n        let specification = validate_common(self.code, self.stage, self.retryable, &self.request_id)?;\n        if self.message_key != specification.message_key {\n            return Err(AuthorityError::InvalidMessageKey);\n        }\n        Ok(())\n    }\n}\n\npub fn decode_internal(error_version: u16, encoded: &str) -> Result<InternalError, AuthorityError> {\n    let value: InternalError = serde_json::from_str(encoded).map_err(|error| AuthorityError::InvalidEnvelope(error.to_string()))?;\n    value.validate(error_version)?;\n    Ok(value)\n}\n\npub fn decode_public(error_version: u16, encoded: &str) -> Result<PublicError, AuthorityError> {\n    let value: PublicError = serde_json::from_str(encoded).map_err(|error| AuthorityError::InvalidEnvelope(error.to_string()))?;\n    value.validate(error_version)?;\n    Ok(value)\n}\n`;
}

const generated = Object.freeze({
  schema: schemaSource(),
  javascript: javascriptSource(),
  go: execFileSync("gofmt", { input: goSource(), encoding: "utf8" }),
  rust: execFileSync("rustfmt", ["--edition", "2024"], { input: rustSource(), encoding: "utf8" }),
});
for (const [name, outputPath] of Object.entries(outputs)) {
  if (mode === "--check") {
    if (await readFile(outputPath, "utf8") !== generated[name]) throw new Error(`generated error authority is stale: ${path.relative(root, outputPath)}`);
  } else {
    await writeFile(outputPath, generated[name]);
  }
}
