use zp_rewriter::{rewrite_script, RewriteOpts, ScriptKind};

fn opts() -> RewriteOpts {
    RewriteOpts {
        kind: ScriptKind::Classic,
        target_url: "https://example.com/".into(),
        strict: true,
        proxy_origin: "http://proxy.localhost:18080".into(),
    }
}

fn show(src: &str) {
    match rewrite_script(src, &opts()) {
        Ok(r) => println!("IN : {src}\nOUT: {}", r.code),
        Err(e) => println!("IN : {src}\nERR: {e:?}"),
    }
    println!("---");
}

#[test]
fn scratch_probe() {
    for src in [
        "for (location of a) {}",
        "for (location in a) {}",
        "for (let location of a) {}",
        "[location] = arr;",
        "({a: location} = obj);",
        "import location from './x.js';",
        "import {location as loc} from './x.js';",
        "class location {}",
        "function f(){ location.x; var location; }",
        "function f(){ location.x; function location(){} }",
        "{ location.x; let location; }",
        "x?.location;",
        "x?.location.href;",
        "delete location.href;",
        "delete obj.location;",
        "this['location'];",
        "document['location'].href = 'https://t/';",
        "with(o){ location.href = 'x'; }",
        "with(o){ f(location); }",
        "eval('x');",
        "location ??= u;",
        "obj.location ??= u;",
        "x ||= y;",
        "loc ||= y;",
        "location?.reload();",
        "switch(location){}",
        "function* g(){ yield location; }",
        "async function f(){ await location; }",
        "label: for(;;){}",
        "for(let i=0;;i++){}",
        "async function f(){ while(true){ await x(); } }",
        "var location;",
        "var location; location.href = 'https://t/';",
        "var document; document['location'].href = 'https://t/';",
        "var location = {href: 1};",
        "function location(){} location.href = 'https://t/';",
        "var eval; eval('x');",
        "var Function; Function('x')();",
        "var window; window['location'].href = 'https://t/';",
        "x?.m();",
        "x?.location?.();",
        "const {location} = x;",
        "let [location] = y;",
        "try{}catch({message: location}){}",
        "new Function('return this')();",
        "f`${location}`;",
        "void location;",
        "typeof location;",
        "location instanceof Location;",
        "location?.['href'];",
        // -- computed member mediation --
        "x[k];",
        "x['location'];",
        "x[k] = v;",
        "x['location'] = v;",
        "x[k]++;",
        "x['location'] += y;",
        "frames[0];",
        "frames[i].location;",
        "x?.[k];",
        "x?.['location'];",
        // -- computed / optional calls --
        "x[k](1,2);",
        "x['location']();",
        "x?.[k](a);",
        "x?.m?.();",
        "x?.[k]?.();",
        "obj.location.assign('u');",
        "history.pushState({},'','/p');",
        // -- Reflect / Object paths --
        "Reflect.get(doc, k);",
        "Reflect.get(doc, 'location');",
        "Reflect.get(obj, 'foo');",
        "Reflect.set(doc, k, v);",
        "Reflect.set(doc, k, v, r);",
        "Reflect.deleteProperty(d, 'location');",
        "Reflect.has(d, 'location');",
        "Reflect.ownKeys(d);",
        "Object.getOwnPropertyDescriptors(doc);",
        "Object.getOwnPropertyNames(doc);",
        "Object.keys(d);",
        // -- eval --
        "eval('location.href');",
        "eval('var q=1; q');",
        "eval(x);",
        "(0,eval)('location');",
        "eval?.('location');",
        "e=eval; e('location');",
        // -- with --
        "with(o){ x = 1; }",
        "with(a){ with(b){ location = u; } }",
        "with(o){ ({location} = y); }",
        "with(o){ delete location; }",
        "with(o){ delete x.p; }",
        // -- for-of/in dangerous targets --
        "for (var location of xs) {}",
        "for (var location in xs) {}",
        "for (var {location} of xs) {}",
        "for ([location] of xs) {}",
        "for ({a: location} of xs) {}",
        // -- loop caps --
        "for(;;){}",
        "for(i=0;;i++){}",
        "for(i=0;true;i++){}",
        "for(const x=0;;x++){}",
        "while(true){}",
        "do{}while(true);",
        "for(i=0;i<n;i++){}",
        // -- loop caps in bare / labeled positions --
        "if(c) for(i=0;;i++) x();",
        "if(c) for(i=0;;i++) x(); else y();",
        "while(c) do{}while(true);",
        "outer: for(i=0;;i++){ if(q) continue outer; if(r) break outer; }",
        "outer: for(;;){ continue outer; }",
        "outer: while(true){ continue outer; }",
        "outer: do{ if(q) continue outer; }while(true);",
        "a: b: for(i=0;;i++){ continue a; break b; }",
        "if(c) while(true) x();",
        "with(o){ if(q) for(i=0;;i++) x(); }",
        // -- misc --
        "var {location} = o;",
        "var [location] = a;",
        "var {a: location} = o;",
        "new.target;",
        "import.meta.url;",
        "delete obj[k];",
        "delete obj?.location;",
        "x.location++;",
        "x.location -= y;",
        "++location;",
        "let l = -location;",
        "location = u, x = 1;",
        "var a = 1, location = 2, b = 3;",
        "function g(location){ location.href; }",
        "(() => { var location = 1; location; })();",
        "if (x) function location(){}",
        "var open; open('u');",
        "export {}; var location; location;",
    ] {
        show(src);
    }
}
