[package]
name = "policy-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type=["cdylib","rlib"]

[dependencies]
base64 = "0.22.1"
serde.workspace = true
sha2 = "0.10.9"
thiserror.workspace = true
url.workspace = true
psl="2.1.218"
serde_json.workspace=true
wasm-bindgen.workspace=true
