// Generated by scripts/generate-policy-inventory.mjs. DO NOT EDIT.

pub fn html_inventory_entry(
    namespace: &str,
    element: &str,
    attribute: &str,
    link_rel: Option<&str>,
    http_equiv: Option<&str>,
    type_essence: Option<&str>,
) -> Option<InventoryEntry> {
    if namespace == "html" && element == "link" && attribute == "href" {
        let mut selected = None;
        for token in link_rel.unwrap_or_default().split_ascii_whitespace() {
                if token.eq_ignore_ascii_case("dns-prefetch") { selected = Some(InventoryEntry { parsing: InventoryParsing::RelTokenDependent, disposition: InventoryDisposition::RemoveHint, resource_kind: None }); }
                if token.eq_ignore_ascii_case("preconnect") { selected = Some(InventoryEntry { parsing: InventoryParsing::RelTokenDependent, disposition: InventoryDisposition::RemoveHint, resource_kind: None }); }
        }
        if selected.is_some() { return selected; }
    }
    if namespace == "html" && element == "link" && attribute == "href" {
        let mut selected = None;
        for token in link_rel.unwrap_or_default().split_ascii_whitespace() {
                if token.eq_ignore_ascii_case("stylesheet") { selected = Some(InventoryEntry { parsing: InventoryParsing::RelTokenDependent, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Style) }); }
                if token.eq_ignore_ascii_case("icon") { selected = Some(InventoryEntry { parsing: InventoryParsing::RelTokenDependent, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Image) }); }
                if token.eq_ignore_ascii_case("apple-touch-icon") { selected = Some(InventoryEntry { parsing: InventoryParsing::RelTokenDependent, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Image) }); }
                if token.eq_ignore_ascii_case("manifest") { selected = Some(InventoryEntry { parsing: InventoryParsing::RelTokenDependent, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Manifest) }); }
                if token.eq_ignore_ascii_case("preload") { selected = Some(InventoryEntry { parsing: InventoryParsing::RelTokenDependent, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Style) }); }
                if token.eq_ignore_ascii_case("modulepreload") { selected = Some(InventoryEntry { parsing: InventoryParsing::RelTokenDependent, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Module) }); }
                if token.eq_ignore_ascii_case("prefetch") { selected = Some(InventoryEntry { parsing: InventoryParsing::RelTokenDependent, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Document) }); }
        }
        if selected.is_some() { return selected; }
    }
    if namespace == "html" && element == "link" && attribute == "imagesrcset" {
        let mut selected = None;
        for token in link_rel.unwrap_or_default().split_ascii_whitespace() {
                if token.eq_ignore_ascii_case("preload") { selected = Some(InventoryEntry { parsing: InventoryParsing::Srcset, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Image) }); }
                if token.eq_ignore_ascii_case("modulepreload") { selected = Some(InventoryEntry { parsing: InventoryParsing::Srcset, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Image) }); }
                if token.eq_ignore_ascii_case("prefetch") { selected = Some(InventoryEntry { parsing: InventoryParsing::Srcset, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Image) }); }
        }
        if selected.is_some() { return selected; }
    }
    if namespace == "html" && element == "base" && attribute == "href" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::VirtualBase, resource_kind: Some(ResourceKind::Document) }); }
    if namespace == "html" && element == "a" && attribute == "href" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledNavigation, resource_kind: Some(ResourceKind::Document) }); }
    if namespace == "html" && element == "area" && attribute == "href" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledNavigation, resource_kind: Some(ResourceKind::Document) }); }
    if namespace == "html" && element == "form" && attribute == "action" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledNavigation, resource_kind: Some(ResourceKind::Document) }); }
    if namespace == "html" && element == "button" && attribute == "formaction" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledNavigation, resource_kind: Some(ResourceKind::Document) }); }
    if namespace == "html" && element == "input" && attribute == "formaction" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledNavigation, resource_kind: Some(ResourceKind::Document) }); }
    if namespace == "html" && element == "iframe" && attribute == "src" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledNavigation, resource_kind: Some(ResourceKind::Frame) }); }
    if namespace == "html" && element == "frame" && attribute == "src" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledNavigation, resource_kind: Some(ResourceKind::Frame) }); }
    if namespace == "html" && element == "img" && attribute == "src" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Image) }); }
    if namespace == "html" && element == "img" && attribute == "srcset" { return Some(InventoryEntry { parsing: InventoryParsing::Srcset, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Image) }); }
    if namespace == "html" && element == "source" && attribute == "src" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Image) }); }
    if namespace == "html" && element == "source" && attribute == "srcset" { return Some(InventoryEntry { parsing: InventoryParsing::Srcset, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Image) }); }
    if namespace == "html" && element == "input" && attribute == "src" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Image) }); }
    if namespace == "html" && element == "video" && attribute == "src" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Media) }); }
    if namespace == "html" && element == "audio" && attribute == "src" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Media) }); }
    if namespace == "html" && element == "track" && attribute == "src" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Media) }); }
    if namespace == "html" && element == "video" && attribute == "poster" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Media) }); }
    if namespace == "html" && element == "script" && attribute == "src" && type_essence.is_some_and(|value| value.eq_ignore_ascii_case("module")) { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledExecutable, resource_kind: Some(ResourceKind::Module) }); }
    if namespace == "html" && element == "script" && attribute == "src" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledExecutable, resource_kind: Some(ResourceKind::Script) }); }
    if namespace == "html" && element == "object" && attribute == "data" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledNavigation, resource_kind: Some(ResourceKind::Document) }); }
    if namespace == "html" && element == "embed" && attribute == "src" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledNavigation, resource_kind: Some(ResourceKind::Document) }); }
    if namespace == "html" && element == "body" && attribute == "background" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Image) }); }
    if namespace == "html" && element == "table" && attribute == "background" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Image) }); }
    if namespace == "html" && element == "td" && attribute == "background" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Image) }); }
    if namespace == "html" && element == "th" && attribute == "background" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Image) }); }
    if namespace == "html" && element == "html" && attribute == "manifest" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Manifest) }); }
    if namespace == "html" && element == "meta" && attribute == "content" && http_equiv.is_some_and(|value| value.eq_ignore_ascii_case("refresh")) { return Some(InventoryEntry { parsing: InventoryParsing::Refresh, disposition: InventoryDisposition::ControlledNavigation, resource_kind: Some(ResourceKind::Document) }); }
    if namespace == "html" && element == "style" && attribute == "text" { return Some(InventoryEntry { parsing: InventoryParsing::Style, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Image) }); }
    if namespace == "html" && true && attribute == "style" { return Some(InventoryEntry { parsing: InventoryParsing::Style, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Image) }); }
    if namespace == "html" && element == "iframe" && attribute == "srcdoc" { return Some(InventoryEntry { parsing: InventoryParsing::Srcdoc, disposition: InventoryDisposition::RecursiveDocument, resource_kind: Some(ResourceKind::Document) }); }
    if namespace == "html" && true && attribute.starts_with("on") { return Some(InventoryEntry { parsing: InventoryParsing::EventHandler, disposition: InventoryDisposition::CompileEventHandler, resource_kind: None }); }
    if namespace == "svg" && element == "image" && attribute == "href" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Image) }); }
    if namespace == "svg" && element == "image" && attribute == "xlink:href" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Image) }); }
    if namespace == "svg" && element == "use" && attribute == "href" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Image) }); }
    if namespace == "svg" && element == "use" && attribute == "xlink:href" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Image) }); }
    if namespace == "svg" && element == "script" && attribute == "href" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::ControlledExecutable, resource_kind: Some(ResourceKind::Script) }); }
    if namespace == "mathml" && element == "annotation-xml" && attribute == "src" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::Block, resource_kind: None }); }
    if namespace == "html" && element == "link" && attribute == "href" { return Some(InventoryEntry { parsing: InventoryParsing::RelTokenDependent, disposition: InventoryDisposition::ControlledFetch, resource_kind: Some(ResourceKind::Style) }); }
    if namespace == "html" && element == "a" && attribute == "ping" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::RemoveHint, resource_kind: None }); }
    if namespace == "html" && element == "area" && attribute == "ping" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::RemoveHint, resource_kind: None }); }
    if namespace == "html" && element == "a" && attribute == "attributionsrc" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::Block, resource_kind: None }); }
    if namespace == "html" && element == "img" && attribute == "attributionsrc" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::Block, resource_kind: None }); }
    if namespace == "html" && element == "script" && attribute == "attributionsrc" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::Block, resource_kind: None }); }
    if namespace == "html" && element == "portal" && attribute == "src" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::Block, resource_kind: None }); }
    if namespace == "html" && element == "fencedframe" && attribute == "src" { return Some(InventoryEntry { parsing: InventoryParsing::SingleUrl, disposition: InventoryDisposition::Block, resource_kind: None }); }
    None
}
