import './zp-core.js';
import 'virtual:zeroproxy-rust-rewriter';
import './http-rewriter.js';
import 'virtual:zeroproxy-wasm-exec';
import './sw/kernel.js';
import './sw/routes.js';
import './sw/transport.js';
import './sw/responses.js';
import 'virtual:zeroproxy-sw-body';
